### ISSUE TITLE
Congrats on the good work!

### ISSUE THREAD

**Issue by DanielCauser** [roubachof/Sharpnado.Presentation.Forms#1]
Hey man, good job on this app! I'm going to use some of it as reference for my self! It is great to see your insights on your blog too, keep the good work, it is great to have you contributing with the community!

Have you heard of Planet Xamarin? It is a content aggregator of all Xamarin Authors, I think you should submit your profile and your blog as Community Authors!

https://www.planetxamarin.com/authors

Once again, congrats!

**Comment by roubachof** [comment]
hey man!
As I said in the post you have my special thanks ;)
For planet Xamarin, you need at least three xamarin posts, so far I have only two, but I will apply next week I guess :)
Long live the community!
