### ISSUE TITLE
TabButton only Accept string in IconImageSource

### ISSUE THREAD

**Issue by moreirawebmaster** [roubachof/Sharpnado.Presentation.Forms#100]
Hello!!!!

Great job in plugin, thanks.

But, TabButton(Center) with property IconImageSource only accept string, this is possible accept ImageSource how ButtomTabItem?

My image is ImageSource.FromResource.

![image](https://user-images.githubusercontent.com/1142139/74368294-20ead600-4db2-11ea-9b0f-e3e7f621c6e3.png)

**Comment by roubachof** [comment]
Will be fixed in the next release
