### ISSUE TITLE
OnTap behavior example?

### ISSUE THREAD

**Issue by SharbelWired** [roubachof/Sharpnado.Presentation.Forms#11]
Hi there, I'm using the Horizontal ListView in an app that I'm developing.  It is rendering fine, but looking at your examples for handling the OnTap event, it is using, from what I can see, some other libraries that I am not really wanting to use.  Question, does the Horizontal ListView support regular behavior declarations in the Xaml like the regular ListView?  When I try to add a behavior node that declares EventToCommandBehavior (EventName="ItemTapped", the app crashes.  Is there an example that I can follow on the correct way to bind this?  I'm using MVVM (Prism), if that matters.

Here's my XAML (I took out the behaviors):

```
<renderedViews:HorizontalListView
                    CollectionPadding="0,8"
                    ItemHeight="125"
                    ItemSpacing="8"
                    ItemWidth="85"
                    ItemsSource="{Binding Winners}"
                    SnapStyle="Start">
                <renderedViews:HorizontalListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <StackLayout>
                                <Image
                                        HorizontalOptions="Center"
                                        Source="{Binding UserProfile.ProfilePicUrl}"
                                        WidthRequest="75"/>
                                <Label
                                        HorizontalOptions="Center"
                                        Text="{Binding UserProfile.FullName}"
                                        FontSize="Micro" />
                                <Label
                                        HorizontalOptions="Center"
                                        Text="{Binding PlaceString}"
                                        FontSize="Medium" />
                            </StackLayout>
                        </ViewCell>
                    </DataTemplate>
                </renderedViews:HorizontalListView.ItemTemplate>
            </renderedViews:HorizontalListView>
```

**Comment by roubachof** [comment]
Hi!
In fact the ```TapCommand``` and ```TapFeedbackColor``` are already included in the project (it’s embedded, not a nuget package reference). It’s just 3 classes per platform so maybe less than 1kb. I used them cause they implement really well the ripple effect on all version of Android, you have also a nice feedback animation on iOS, and you can specify the tap feedback color.

**Comment by SharbelWired** [comment]
Thank-you.  Is there a sample on how to call the TapCommand and where to define it in the Xaml?  I'm looking at your silly people sample app but I do not see where you're defining the OnTap command anywhere.

**Comment by SharbelWired** [comment]
Yes, I did see and try this in my project but the command does not get triggered.  I cloned your example project and now see that your commands are a custom "AsynCommand", not just a regular ICommand that I was creating in my VM.  I wonder if that is the issue?  Just to be clear, where you have {Binding OnItemTappedCommand}, I put this into my Xaml View, added relevant references, and added an ICommand in my VM, but when I tap the image element in the item template that I bind the command to, it doesn't trigger the command when tapped.   Do I need to use the AsyncCommand class?

**Comment by roubachof** [comment]
Nope Command or AsyncCommand should work...
Are you sure you passed the Command to the view model items and not the parent view model (in the silly app case SillyDudeVmo and not SillyPeopleVm) ?

**Comment by roubachof** [comment]
Closed since no news since 1 month.

**Comment by amirvenus** [comment]
Where is `views:SillySquareCell ?`

I am struggling to find its namespace

**Comment by NickeManarin** [comment]
@SharbelWired Yeah, it's not triggering with me too. Not even the Tapped event is firing. I've tried with a DraggableViewCell, ViewCell, CustomViewCell (with a custom command and a OnTapped override).

That's strange.

**Comment by NickeManarin** [comment]
> Where is views:SillySquareCell ?
> I am struggling to find its namespace

[It's here](https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/Views/SillySquareCell.xaml), it's a simple ViewCell.

**Comment by NickeManarin** [comment]
@roubachof I'm testing with an emulator (since there's a pretty serious bug with Xamarin.Forms/mono right now), perhaps that's an issue?
