### ISSUE TITLE
ItemSource System.Invalid Cast Exception Specified cast is not valid.

### ISSUE THREAD

**Issue by kebaranas** [roubachof/Sharpnado.Presentation.Forms#110]
**Platform (please complete the following information):**
 - OS: Both
 - Device: Samsung A6 2017
 - Sdk vervion: Android SDK 28
 - Xamarin.Forms: latest

**Describe the bug**
As far as I can observe it raises when I bind an observable collection to ItemSource.

**To Reproduce**
1. Bind observable collection to the ItemSource of the HorizontalListView.
**Exceptions (if applicable)**
System.InvalidCastException: 'Specified cast is not valid.'

**Screenshots (if applicable)**

**Comment by roubachof** [comment]
need complete exception stack.

**Comment by kebaranas** [comment]
0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120,4	C#
 	0x2D in Android.Runtime.DynamicMethodNameCounter.84	C#
 	0x15 in Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.AndroidHorizontalListViewRenderer.RecycleViewAdapter.CreateView at D:\Dev\Sharpnado\src\Xamarin-Forms-Practices\Sharpnado.Presentation.Forms\Sharpnado.Presentation.Forms.Droid\Renderers\HorizontalList\AndroidHorizontalListViewRenderer.RecycleViewAdapter.cs:283,21	C#
 	0x4 in Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.AndroidHorizontalListViewRenderer.RecycleViewAdapter.CreateViewHolder at D:\Dev\Sharpnado\src\Xamarin-Forms-Practices\Sharpnado.Presentation.Forms\Sharpnado.Presentation.Forms.Droid\Renderers\HorizontalList\AndroidHorizontalListViewRenderer.RecycleViewAdapter.cs:272,17	C#
 	0x2 in Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.AndroidHorizontalListViewRenderer.RecycleViewAdapter.<.ctor>b__12_0 at D:\Dev\Sharpnado\src\Xamarin-Forms-Practices\Sharpnado.Presentation.Forms\Sharpnado.Presentation.Forms.Droid\Renderers\HorizontalList\AndroidHorizontalListViewRenderer.RecycleViewAdapter.cs:138,89	C#
 	0x49 in Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.ViewHolderQueue.Dequeue at D:\Dev\Sharpnado\src\Xamarin-Forms-Practices\Sharpnado.Presentation.Forms\Sharpnado.Presentation.Forms.Droid\Renderers\HorizontalList\ViewHolderQueue.cs:67,13	C#
 	0x34 in Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.AndroidHorizontalListViewRenderer.RecycleViewAdapter.OnCreateViewHolder at D:\Dev\Sharpnado\src\Xamarin-Forms-Practices\Sharpnado.Presentation.Forms\Sharpnado.Presentation.Forms.Droid\Renderers\HorizontalList\AndroidHorizontalListViewRenderer.RecycleViewAdapter.cs:203,17	C#
 	0x12 in Android.Support.V7.Widget.RecyclerView.Adapter.n_OnCreateViewHolder_Landroid_view_ViewGroup_I	C#
 	0x1D in Android.Runtime.DynamicMethodNameCounter.84	C#
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#
 	0x21 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod	C#
 	0x3C in Android.Views.View.Measure	C#
 	0x34 in Xamarin.Forms.Platform.Android.ViewRenderer<Sharpnado.Presentation.Forms.RenderedViews.HorizontalListView,Android.Support.V7.Widget.RecyclerView>.GetDesiredSize at D:\a\1\s\Xamarin.Forms.Platform.Android\ViewRenderer.cs:135,4	C#
 	0xB3 in Xamarin.Forms.Platform.Android.Platform.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:1358,4	C#
 	0x3 in Xamarin.Forms.Forms.AndroidPlatformServices.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Forms.cs:930,5	C#
 	0x2D in Xamarin.Forms.VisualElement.OnSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:800,4	C#
 	0x3 in Xamarin.Forms.VisualElement.OnMeasure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:783,4	C#
 	0x56 in Xamarin.Forms.VisualElement.GetSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:659,4	C#
 	0x57 in Xamarin.Forms.VisualElement.Measure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:717,4	C#
 	0xEC in Xamarin.Forms.Grid.CalculateAutoCells at D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:133,8	C#
 	0xF in Xamarin.Forms.Grid.MeasureGrid at D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:485,4	C#
 	0x2E in Xamarin.Forms.Grid.OnSizeRequest at D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:60,4	C#
 	0x3 in Xamarin.Forms.VisualElement.OnMeasure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:783,4	C#
 	0x56 in Xamarin.Forms.VisualElement.GetSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:659,4	C#
 	0x21 in Xamarin.Forms.Layout.GetSizeRequest at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:132,4	C#
 	0x57 in Xamarin.Forms.VisualElement.Measure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:717,4	C#
 	0xF2 in Xamarin.Forms.ScrollView.LayoutChildren at D:\a\1\s\Xamarin.Forms.Core\ScrollView.cs:236,7	C#
 	0x160 in Xamarin.Forms.Layout.UpdateChildrenLayout at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266,4	C#
 	0x10 in Xamarin.Forms.Layout.OnSizeAllocated at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224,4	C#
 	0x3 in Xamarin.Forms.VisualElement.SizeAllocated at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:805,4	C#
 	0x24 in Xamarin.Forms.VisualElement.SetSize at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:1084,4	C#
 	0x6C in Xamarin.Forms.VisualElement.set_Bounds at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:320,5	C#
 	0x2 in Xamarin.Forms.VisualElement.Layout at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:701,4	C#
 	0x1DC in Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:178,4	C#
 	0x24 in Xamarin.Forms.TemplatedView.LayoutChildren at D:\a\1\s\Xamarin.Forms.Core\TemplatedView.cs:29,6	C#
 	0x160 in Xamarin.Forms.Layout.UpdateChildrenLayout at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266,4	C#
 	0x10 in Xamarin.Forms.Layout.OnSizeAllocated at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224,4	C#
 	0x3 in Xamarin.Forms.VisualElement.SizeAllocated at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:805,4	C#
 	0x24 in Xamarin.Forms.VisualElement.SetSize at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:1084,4	C#
 	0x6C in Xamarin.Forms.VisualElement.set_Bounds at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:320,5	C#
 	0x2 in Xamarin.Forms.VisualElement.Layout at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:701,4	C#
 	0x1DC in Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:178,4	C#
 	0x110 in Xamarin.Forms.Page.LayoutChildren at D:\a\1\s\Xamarin.Forms.Core\Page.cs:285,6	C#
 	0xD0 in Xamarin.Forms.Page.UpdateChildrenLayout at D:\a\1\s\Xamarin.Forms.Core\Page.cs:361,4	C#
 	0x10 in Xamarin.Forms.Page.OnSizeAllocated at D:\a\1\s\Xamarin.Forms.Core\Page.cs:341,4	C#
 	0x3 in Xamarin.Forms.VisualElement.SizeAllocated at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:805,4	C#
 	0x24 in Xamarin.Forms.VisualElement.SetSize at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:1084,4	C#
 	0x6C in Xamarin.Forms.VisualElement.set_Bounds at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:320,5	C#
 	0x2 in Xamarin.Forms.VisualElement.Layout at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:701,4	C#
 	0x61 in Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:147,5	C#
 	0x110 in Xamarin.Forms.Page.LayoutChildren at D:\a\1\s\Xamarin.Forms.Core\Page.cs:285,6	C#
 	0xD0 in Xamarin.Forms.Page.UpdateChildrenLayout at D:\a\1\s\Xamarin.Forms.Core\Page.cs:361,4	C#
 	0x10 in Xamarin.Forms.Page.OnSizeAllocated at D:\a\1\s\Xamarin.Forms.Core\Page.cs:341,4	C#
 	0x3 in Xamarin.Forms.VisualElement.SizeAllocated at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:805,4	C#
 	0xB6 in Xamarin.Forms.Page.OnChildMeasureInvalidated at D:\a\1\s\Xamarin.Forms.Core\Page.cs:400,5	C#
 	0x1B in Xamarin.Forms.Page.OnChildMeasureInvalidated at D:\a\1\s\Xamarin.Forms.Core\Page.cs:323,4	C#
 	0x1D in Xamarin.Forms.VisualElement.InvalidateMeasureInternal at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:837,4	C#
 	0x1F in Xamarin.Forms.VisualElement.set_IsPlatformEnabled at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:552,6	C#
 	0xF in Xamarin.Forms.Platform.Android.Platform.<>c.<.cctor>b__125_0 at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:46,6	C#
 	0x12E in Xamarin.Forms.BindableObject.SetValueActual at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:463,5	C#
 	0x17C in Xamarin.Forms.BindableObject.SetValueCore at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397,5	C#
 	0x56 in Xamarin.Forms.BindableObject.SetValue at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:334,4	C#
 	0x5 in Xamarin.Forms.BindableObject.SetValue at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:311,68	C#
 	0x7 in Xamarin.Forms.Platform.Android.Platform.SetRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:369,4	C#
 	0x31 in Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:65,5	C#
 	0x24 in Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_	C#
 	0x23 in Android.Runtime.DynamicMethodNameCounter.43	C#
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#
 	0x21 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod	C#
 	0x3C in Android.Views.View.Measure	C#
 	0x48 in Xamarin.Forms.Platform.Android.AppCompat.TabbedPageRenderer.OnLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\TabbedPageRenderer.cs:401,5	C#
 	0x10 in Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII at D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:198,4	C#
 	0x2F in Android.Runtime.DynamicMethodNameCounter.33	C#
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#
 	0x5F in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod	C#
 	0x97 in Xamarin.Forms.Platform.Android.FormsViewGroup.MeasureAndLayout at D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:181,5	C#
 	0x171 in Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:111,5	C#
 	0x1E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.TabbedPage>.UpdateLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:142,4	C#
 	0x3A in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.NavigationPage>.UpdateLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:409,5	C#
 	0x1E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.NavigationPage>.OnLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:394,4	C#
 	0x15 in Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:414,4	C#
 	0x10 in Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII at D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:198,4	C#
 	0x2F in Android.Runtime.DynamicMethodNameCounter.33	C#
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#
 	0x5F in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod	C#
 	0x97 in Xamarin.Forms.Platform.Android.FormsViewGroup.MeasureAndLayout at D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:181,5	C#
 	0x171 in Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:111,5	C#
 	0x1E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.NavigationPage>.UpdateLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:142,4	C#
 	0x2B in Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:235,4	C#
 	0x2D in Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout at D:\a\1\s\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:75,4	C#
 	0x12 in Android.Views.ViewGroup.n_OnLayout_ZIIII	C#
 	0x2F in Android.Runtime.DynamicMethodNameCounter.35	C#

**Comment by roubachof** [comment]
in Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.AndroidHorizontalListViewRenderer.RecycleViewAdapter.CreateView at D:\Dev\Sharpnado\src\Xamarin-Forms-Practices\Sharpnado.Presentation.Forms\Sharpnado.Presentation.Forms.Droid\Renderers\HorizontalList\AndroidHorizontalListViewRenderer.RecycleViewAdapter.cs:283,21

```csharp
viewCell = (ViewCell)dataTemplate.CreateContent();
```

The horizontal list view only accept `ViewCell` type as `DataTemplate`
