### ISSUE TITLE
Item Being Dragged

### ISSUE THREAD

**Issue by jamsoft** [roubachof/Sharpnado.Presentation.Forms#112]
I'm looking over the code and trying to see if there is any way to get hold of the item currently being dragged in the UI?

I couldn't see anything natively inside the control code.

**Comment by roubachof** [comment]
you can use https://github.com/roubachof/Sharpnado.Presentation.Forms/wiki/HorizontalListView-Grid-And-Carousel#draggableviewcell instead of a regular `ViewCell`

**Comment by jamsoft** [comment]
Thank you again!
