### ISSUE TITLE
Dragging Item to Different List

### ISSUE THREAD

**Issue by jamsoft** [roubachof/Sharpnado.Presentation.Forms#113]
Promise this is the last one. I need to implement dragging between lists and I suspect the best way will be a behaviour of some description.

Before I go ahead and start building this I wanted to check that I haven't missed some built in feature or existing example in the Silly App that handles such a scenario?

**Comment by roubachof** [comment]
Nah, not handled :)

**Comment by jamsoft** [comment]
Added to the list ... ;)

PS: Your mother smells of Elderberry!

**Comment by roubachof** [comment]
I fart in your general direction!
Now go away or I will taunt you a second time.

**Comment by jamsoft** [comment]
I raise you an African Swallow!!!

I'm feeling a bit out of my depth here. I've been looking at creating a behaviour for this and I've come to the conclusion that I cannot do it with just a behaviour. Unless I've completely missed something obviously there aren't any events to attach to.

However, googling has turned up so many different approaches I've entered the land of the fog of doom (just south of Camelot).

Looking at this java example

https://github.com/pooja-gaikwad15/recyclerview-list-drag-and-drop/blob/master/app/src/main/java/com/test/dragdroptest/CustomListAdapter.java

Has the secret sauce in the onDrag method but this is using the old `DragListener` approach rather than the `ItemTouchHelper` approach.

Do you know of any examples that might nudge me in the right direction? I've been reading for the last 6 hours with no real lightbulb moment so far.

**Comment by jamsoft** [comment]
Ahhh, I've just [discovered](https://stackoverflow.com/a/50344856/155926) that the `ItemTouchHelper` isn't designed for this use case. Only for moving things within a single recyclerview instance.

**Comment by jamsoft** [comment]
No, actually. I am genuinely stumped so I've moved this to [SO](https://stackoverflow.com/questions/61937508/xamarin-forms-android-recyclerview-drag-drop-to-another-recyclerview).

Sorry for all the spam.

**Comment by roubachof** [comment]
I don't think it will happen anytime soon :)
Feel free to reopen the issue if it will :)
