### ISSUE TITLE
Bind tabs

### ISSUE THREAD

**Issue by SorinMiron** [roubachof/Sharpnado.Presentation.Forms#116]
Is there a way to bind tabs for TabHostView? Like itemsource or something else? I can figured out how to add tabs trough TabHost object that is accessible in my View.xaml.cs. The problem is that i want to add/remove tabs from ViewModel. If the TabHost will be accessible in ViewModel, the mvvm practices will be violated. 

Thanks in advance.

**Comment by roubachof** [comment]
For now you can use the view's code behind to add or remove tabs dynamically.

duplicate of #101
