### ISSUE TITLE
Which Android versions are supported?

### ISSUE THREAD

**Issue by Healios** [roubachof/Sharpnado.Presentation.Forms#118]
**Describe the solution you'd like**
I would like for the README to include a section about supported Android versions (iOS as well, I guess).
Support for Android API level 17 would be great too.

**Comment by roubachof** [comment]
Well it depends on the library.
Sharpnado.Shadows should now support api 17 (https://github.com/roubachof/Sharpnado.Shadows/issues/4)
MaterialFrame also
normally it should support the recommended Android version for Xamarin.Forms (api 21, but could work on 19 :)

**Comment by Healios** [comment]
Fair point :) - _(Originally I thought about the whole thing, but now it's specifically the Shadows package)_

Do you have an idea of when a new NuGet will be released?

Also, you've made some awesome packages and I hope you keep at it!

**Comment by roubachof** [comment]
_In fact I knew you were talking about Shadows cause I saw the first edition of your post :p (ty gmail notifications)_

Well I dunno... when I won't be lazy about it since I guess since it is really a 5 minutes operation. But yet 5 boring minutes x)

**Comment by Healios** [comment]
_My lord, you've gone mad with power._

Alright, well, when you do come around to it, you'll be making someone (ME) very happy :) - I have to comment out the shadows until the new package has arrived.
