### ISSUE TITLE
Problems with the sizing of the HorizontalListView in Grid mode

### ISSUE THREAD

**Issue by LegendaryB** [roubachof/Sharpnado.Presentation.Forms#119]
Hey dude,

first of all: Thanks for your awesome work on this :)

Now to my problem:
I'm using the Grid inside of a page with other elements and have sizing problems. Does the control has any method to resize its height according to its child elements? So that height equals rows * rowheight?
Maybe it does not work out of the box because a scroll view is internally used? Just guessing here.

Also it seems like the control ignores height requests. Got resize somehow only working with the options (Vertical, horizontal)

**Comment by roubachof** [comment]
hey !

Nope it does not, if you want to have exactly the good height, just do the math and put it in a Grid with the according height or a StackLayout with VerticalOptions=Center or whatever and a HeightRequest.
You can also create a converter that will take row count and the row height and return the sum and bind it to HeightRequest or RowDefinition Height.

**Comment by LegendaryB** [comment]
Damn dude who are you? Fastest response I ever got :D
Okay yeah thought also about this as a workaround. But in general would you be open for pull requests regarding this? Maybe make this optional with an extra property?

**Comment by roubachof** [comment]
I could be, but you will have to be very careful for possible misconfigurations.
Also respect the coding style don't import yours :)
You could begin by creating a Spec issue, then if it seems good to me, you could go.

**Comment by LegendaryB** [comment]
Okay did test around with height request. But it is just ignored. 
Have the following Layout:
Stacklayout as Container for the Page ->
  -> Label 1
  -> Label 2
  -> Your ListView
  -> Label
  -> Button

So nothing fancy and no nesting or stuff like this. On the ListView I set the HeightRequest to 500 and also the MinimumHeightRequest to 500 to "force" it. But the View stays in its original size. Any ideas? Or do you need more information?

**Comment by roubachof** [comment]
is "VerticalOption=Center" on the HLV ?

**Comment by LegendaryB** [comment]
Yes it is.

I use it like this:
```
<renderedviews:HorizontalListView
            BackgroundColor="Yellow"
            CollectionPadding="16"
            ColumnCount="3"
            DisableScroll="True"
            EnableDragAndDrop="True"
            HeightRequest="600"
            ItemHeight="130"
            ItemSpacing="8"
            ItemWidth="100"
            ItemsSource="{Binding Images}"
            ListLayout="Grid"
            MinimumHeightRequest="500"
            VerticalOptions="Center">
```

**Comment by roubachof** [comment]
damn it!
will need a repro sample :)

**Comment by LegendaryB** [comment]
Will try to create one. But maybe not today. So I will create it tomorrow at work. I also just have tested on iOS. Maybe its platform specific dunno. Just as extra info ^^

**Comment by roubachof** [comment]
Oh there is no hurry :)
Also, test it on Android, it will give me more context.

**Comment by LegendaryB** [comment]
Will finish the sample today. At the first look I think it is a iOS specific problem. But we will see

**Comment by LegendaryB** [comment]
Okay here is the sample: https://github.com/LegendaryB/Sharpnado.Presentation.Forms-Issue119

Informations:
- On iOS the size is not adjusted and just ignored
- On Android the control uses the given size but is not even displaying the (string) items

**Comment by LegendaryB** [comment]
Any news about this? Sorry to ask again but is somehow really a showstopper currently ^^

**Comment by roubachof** [comment]
yeah no. It won't happen quickly. But you can have a look at the ios renderer, a little PR won't be of any harm :)

**Comment by roubachof** [comment]
So it's working on Android with these properties:

```xml
<renderedviews:HorizontalListView
            BackgroundColor="Yellow"
            CollectionPadding="16"
            ColumnCount="3"
            DisableScroll="True"
            EnableDragAndDrop="True"
            ItemHeight="130"
            ItemSpacing="8"
            HeightRequest="300"
            ItemsSource="{Binding Images}"
            ListLayout="Grid">
```

you don't need to specify ItemWidth since it's computed from the ColumnCount.
For iOS I'm testing right now, but I think I found the error.

**Comment by roubachof** [comment]
![image](https://user-images.githubusercontent.com/596903/87146798-c6e03500-c2ab-11ea-9d70-4210bf55d78c.png)

**Comment by roubachof** [comment]
would you be so kind and beta test the package?

[Sharpnado.Forms.HorizontalListView.1.7.1.nupkg.zip](https://github.com/roubachof/Sharpnado.Presentation.Forms/files/4902739/Sharpnado.Forms.HorizontalListView.1.7.1.nupkg.zip)

**Comment by LegendaryB** [comment]
Hey sorry for my late response. I'm currently moving to a new apartment so I can't test it now. Will ping back here when I was able to do it
