### ISSUE TITLE
EmptyView?

### ISSUE THREAD

**Issue by LegendaryB** [roubachof/Sharpnado.Presentation.Forms#120]
Hey,

me again.
Does the HorizontalListView supports a empty view like the official Xamarin Forms CollectionView? Searched for a property but did not found one. Also tried the ControlTemplate way but the control does not have this property.
Next attempt was to subclass it and doing something like this:

```
if (ItemsSource == null || !ItemsSource.Any())
{
   Children.Clear();
   Children.Add(EmptyView)
}
```

Obviously this wasn't working either because there is no Children property.
Any ideas?

**Comment by roubachof** [comment]
All empty views in my projects are handled by the https://github.com/roubachof/Sharpnado.TaskLoaderView
