### ISSUE TITLE
Add XmlnsDefinition

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [roubachof/Sharpnado.Presentation.Forms#121]
Hello. First of all I want to say thank you so much for your work! I have a request / suggestion - consider adding XmlnsDefinition so that you do not separately connect each namespace in xaml this adds extra code. For instance:

```C#
[assembly: Preserve]
[assembly: XmlnsDefinition ("http://sharpnado.net/xamforms", "Sharpnado.Presentation.Forms.CustomViews.Tabs")]
[assembly: XmlnsDefinition ("http://sharpnado.net/xamforms", "Sharpnado.Presentation.Forms.RenderedViews")]
etc...
```
Then use in Xaml will be a little shorter.
Before:
```C#
<ContentPage xmlns:tabs="clr-namespace:Sharpnado.Presentation.Forms.CustomViews.Tabs;assembly=Sharpnado.Presentation.Forms"
             xmlns:renderedViews="clr-namespace:Sharpnado.Presentation.Forms.RenderedViews;assembly=Sharpnado.Presentation.Forms">
			
            <renderedViews:HorizontalListView>
                ....
            </renderedViews:HorizontalListView>

            <tabs:ViewSwitcher>
                ...
           </tabs:ViewSwitcher>
```
After:
```C#
<ContentPage xmlns:sn="http://sharpnado.net/xamforms">
			
            <sn:HorizontalListView>
                ....
            </sn:HorizontalListView>

            <sn:ViewSwitcher>
                ...
           </sn:ViewSwitcher>
```
Documentation: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/custom-namespace-schemas
Thank you for your attention.

**Comment by roubachof** [comment]
I tried using it, but unfortunately it wasn't recognized by the Xaml intellisense.
I also tried using PreferedPrefix attribute, with same disappointment :)

**Comment by AgPeHaJIuH1** [comment]
I use Resharper and it works great. I have my own library for personal use, in which I created a file in the root of the AssemblyInfo.cs project with the contents:
```C#
using Xamarin.Forms;
using Xamarin.Forms.Internals;

[assembly: Preserve]
[assembly: XmlnsDefinition("http://agpehajiuh.net/xamforms", "AgPeHaJIuH.XamForms.Controls")]
[assembly: XmlnsDefinition("http://agpehajiuh.net/xamforms", "AgPeHaJIuH.XamForms.Converters")]
[assembly: XmlnsDefinition("http://agpehajiuh.net/xamforms", "AgPeHaJIuH.XamForms.Dialogs")]
[assembly: XmlnsDefinition("http://agpehajiuh.net/xamforms", "AgPeHaJIuH.XamForms.Gestures")]
[assembly: XmlnsDefinition("http://agpehajiuh.net/xamforms", "AgPeHaJIuH.XamForms.Helpers")]
[assembly: XmlnsDefinition("http://agpehajiuh.net/xamforms", "AgPeHaJIuH.XamForms.Effects")]
[assembly: XmlnsDefinition("http://agpehajiuh.net/xamforms", "AgPeHaJIuH.XamForms.MarkupExtensions")]
```
In other projects I refer like this:
```C#
xmlns:agp="http://agpehajiuh.net/xamforms"
```
And everything works fine.

**Comment by roubachof** [comment]
well I'm using resharper also and had no luck with it *sigh*

**Comment by AgPeHaJIuH1** [comment]
Have you placed these directives at the root of the Sharpnado.Presentation.Forms project?

**Comment by AgPeHaJIuH1** [comment]
There is one limitation. You cannot reference this namespace from the same project where it was declared. Only from other projects that will use the already compiled library. Maybe this was the problem?

**Comment by AgPeHaJIuH1** [comment]
I copied your repository, added XmlnsDefinition. Then I created a new Xamarin.Forms project and tried it, everything works! Can I somehow give you a project in a zip archive, for example?
PS I'm not very good at handling Github ...

**Comment by AgPeHaJIuH1** [comment]
[TestApp.zip](https://github.com/roubachof/Sharpnado.Presentation.Forms/files/4899091/TestApp.zip)
see TestApp\TestApp\Views\AboutPage.xaml

**Comment by roubachof** [comment]
done !
