### ISSUE TITLE
SelectedTabIndexChanged

### ISSUE THREAD

**Issue by angelru** [roubachof/Sharpnado.Presentation.Forms#123]
I have noticed that the command is called several times ... how is the correct way to do it, to know which tab I have pressed?

 ```
<tabs:TabHostView.Behaviors>
<b:EventToCommandBehavior EventName="SelectedTabIndexChanged" Command="{Binding ExampleCommand}" />
</tabs:TabHostView.Behaviors>
```

**Comment by roubachof** [comment]
You can bind ont the `IsSelected` property of the `TabItem`.

**Comment by angelru** [comment]
Thanks!

**Comment by angelru** [comment]
@roubachof 
I have a view that shares the same view and data model, I need to pass it a different parameter to retrieve different data, this is the approach I am using:

```
        public int SelectedViewModelIndex
        {
            get => _selectedViewModelIndex;
            set
            {
                SetProperty(ref _selectedViewModelIndex, value);
                ChatOptionsLoader.Load(LoadOptionsAsync);
            }
        }

        private async Task LoadOptionsAsync()
        {
            if (_selectedViewModelIndex is 0) 
            {
              
            }
            else
            {
             
            }
        }
```

**Comment by roubachof** [comment]
use it like this:

        public int SelectedViewModelIndex
        {
            get => _selectedViewModelIndex;
            set
            {
                if (SetProperty(ref _selectedViewModelIndex, value))
                {
                    ChatOptionsLoader.Load(LoadOptionsAsync);
                }
            }
        }

        private async Task LoadOptionsAsync()
        {
            if (_selectedViewModelIndex is 0) 
            {
              await Service.GetInfo(User.Rooms);
            }
            else
            {
               await Service.GetInfo(User.ExitRoom);
            }
        }

It will be called just once

**Comment by angelru** [comment]
thanks!

**Comment by Kapusch** [comment]
I was also surprised to discover n events triggered if n tabs are displayed.

Here is a workaround I use in my app, it's about adding a TapGestureRecognizer for each tab :
```
<tabs:UnderlinedTabItem.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding SelectSecondTabCommand}" NumberOfTapsRequired="1" /> 
</tabs:UnderlinedTabItem.GestureRecognizers>
```

So that it triggers only once the targeted command with the parameters you want.
