### ISSUE TITLE
Not able to save reordered horizontal listview

### ISSUE THREAD

**Issue by shobhit9243** [roubachof/Sharpnado.Presentation.Forms#125]
I am able to use the drag drop feature but I am not able to see any command or event that gives the new list with updated indexes. Please Help.

**Comment by shobhit9243** [comment]
@roubachof  Please help.

**Comment by roubachof** [comment]
Just bind it to an ObservableCollection like here: https://www.github.com/roubachof/Xamarin-Forms-Practices/tree/master/SillyCompany.Mobile.Practices%2FPresentation%2FViewModels%2FTabsLayout%2FGridPageViewModel.cs

**Comment by shobhit9243** [comment]
@roubachof Thank you so much. This was a great help. One more thing , is there any header and footer available?

**Comment by roubachof** [comment]
Nope
