### ISSUE TITLE
Task.Delay(500) in AndroidHorizontalListViewRenderer

### ISSUE THREAD

**Issue by stefanbogaard86** [roubachof/Sharpnado.Presentation.Forms#13]
**Platform (please complete the following information):**
 - OS: [Android]
 - Device: [all]

**Describe the bug**
First things first, thanks for creating all these great controls, I really enjoy using them, keep it up!

I've noticed updates to the CurrentIndex property of the HorizontalListView on android devices are received with a delay. When I looked into the issue further I found an await Task.Delay(500); inside the AndroidHorizontalListViewRenderer.OnControlScrollChangedListener.cs in the UpdateCurrentIndexAsync method. I'm assuming this delay is unintentional.

[Sharpnado.Presentation.Forms/Sharpnado.Presentation.Forms.Droid/Renderers/HorizontalList/AndroidHorizontalListViewRenderer.OnControlScrollChangedListener.cs ](url)

**Comment by roubachof** [comment]
True. This was for a special case that this lib shouldn't take care of.

**Comment by roubachof** [comment]
fixed in 0.9.7
