### ISSUE TITLE
No working with Android 10

### ISSUE THREAD

**Issue by vipulbuoyancy** [roubachof/Sharpnado.Presentation.Forms#142]
It is working fine up to Android 9, but when I upgraded to Android 10 it started throwing error. Looks like it doesn't have support of appxcomment. Please find the attached image.
![Inkedimage_2021_03_15T16_13_50_242Z_LI](https://user-images.githubusercontent.com/80636669/111299322-ce937d00-8675-11eb-9f8d-bb9e309cea0c.jpg)

**Comment by roubachof** [comment]
Hi there there are no more support for Sharpnado.Presentation.Forms package.
The preferred way is now to install only the packages you need.
