### ISSUE TITLE
HorizontalListView not showing in v0.9.7

### ISSUE THREAD

**Issue by LeoJHarris** [roubachof/Sharpnado.Presentation.Forms#15]
**Platform (please complete the following information):**
 - OS: untested
 - Device: android 5.1.1

**Describe the bug**
As off latest 0.9.7 the HorizontalListView is not displaying on android. When rolling back to previous version it appears again with code unchanged.

**Comment by roubachof** [comment]
Hi!

I need at least the xamarin forms version and the xaml including the horizontal list view.

**Comment by LeoJHarris** [comment]
Xamarin forms version is 3.4.0.1008975

[horizontalListViewXaml.txt](https://github.com/roubachof/Sharpnado.Presentation.Forms/files/2692736/horizontalListViewXaml.txt)

**Comment by roubachof** [comment]
Ok so I got it...
I just defaulted the ItemWidth and height to 0 in this release to force user to specify ```ItemHeight``` and ```ItemWidth```. The default value of 100 just made no sense and had no semantic.

So if you want the same behavior than before, just add ItemWidth=100.

Now I should have thrown exception if ItemHeight or ItemWidth are equal to 0 to make it clear.

Two others suggestions:

### AcitivityLoader and IsVisible

I created a component to take care of your views visibilities depending on an async task being loaded.
I think you will be interested in the TaskLoaderView of the Sharpnado.Forms.Presentation package.

You can have a look here:

https://www.sharpnado.com/taskloaderview-async-init-made-easy/

### TapGestureRecognizer vs TapCommandEffect

You are using a TapGestureRecognizer on the grid:

```xml
<Grid.GestureRecognizers>
                                        <TapGestureRecognizer Command="{Binding OnRecipientTappedCommand}" CommandParameter="{Binding .}" />
                                    </Grid.GestureRecognizers>
```

You could use the ```TapCommandEffect``` embedded with the ```HorizontalListView``` it would give you a nice ripple feedback:

From https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/Views/SillyInfinitePeoplePage.xaml :
```xml
            <DataTemplate x:Key="SillyDataTemplate">
                <ViewCell>
                    <views:SillySquareCell effects:TapCommandEffect.Tap="{Binding OnItemTappedCommand}"
                                           effects:TapCommandEffect.TapParameter="{Binding .}"
                                           effects:ViewEffect.TouchFeedbackColor="{StaticResource Accent}" />
                </ViewCell>
            </DataTemplate>
```

**Comment by roubachof** [comment]
closing for lack of answer.
