### ISSUE TITLE
Rotatory Carousel View

### ISSUE THREAD

**Issue by muhaym** [roubachof/Sharpnado.Presentation.Forms#17]
**Is your feature request related to a problem? Please describe.**
Ability to show previous and next image preview in Horizontal ListView
![image](https://user-images.githubusercontent.com/10905479/50896584-71656680-142f-11e9-93c7-984fd2fb19c2.png)

**Describe the solution you'd like**
Multiple Options where Scaling for current items, scaling for previous and next items, and number of items to be shown at a time. Handling these will ensure it can be used as normal horizontal listview

**Describe alternatives you've considered**
Recently I have written binding for native Android library, 
https://github.com/muhaym/DiscreteScrollView.Xamarin

Also this iOS library is the inspiration for many designers
https://github.com/nicklockwood/iCarousel

**Comment by roubachof** [comment]
resources:

**Android:** https://stackoverflow.com/questions/35309710/zoom-central-image-recycler-view/35311728#35311728

**iOS:**

* https://vidbyte.com/view/ebCRIlG9UDA
* https://stackoverflow.com/questions/45383395/how-to-create-horizontal-carousel-in-ios-10-swift-3

**Comment by roubachof** [comment]
won't be implemented.
