### ISSUE TITLE
CurrentIndex property on Android incorrect

### ISSUE THREAD

**Issue by TheWraithL98** [roubachof/Sharpnado.Presentation.Forms#18]
OS: Android only
Device: Samsung S7, S9 and generic emulator

On Android, the CurrentIndex property seems to be whatever element is the left-most one.  So If you have 3 elements - indexed as 0,1,2, if you are snapped to element 1, since element 0 is still in the viewport, CurrentIndex is 0. CurrentIndex should be the currently snapped element.

**Comment by arctouch-fabriciomiranda** [comment]
Having the same problem above.

**Comment by roubachof** [comment]
hi guys,

This is fixed in 0.9.9.

I had to change the snap center behavior because it was inconsistent between iOS and Android, please read the release note:

https://github.com/roubachof/Sharpnado.Presentation.Forms/releases/tag/v0.9.9

**Comment by TheWraithL98** [comment]
I pulled the .9.9 Nuget package and confirmed - this is working for me.

**Comment by jocontacter** [comment]
One more error: when binded itemssource replaced - CurrentIndex stays in previous index but control shows 0-indexed item. Not sure if i can control shown item by changing CurrentIndex. 
whatever it was, this is awesome control! Thank you!
