### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by alexrysgspr** [roubachof/Sharpnado.Presentation.Forms#2]
Where's the right place to put my logger class if i want to log the exceptions?

**Comment by roubachof** [comment]
You could log the exceptions in the errorHandler you pass to the `ViewModelLoader`

` public ViewModelLoader(Func<Exception, string> errorHandler = null, string emptyStateMessage = null)`

```csharp
        public static string ToString(Exception exception)
        {
            Log.Error($"Loading task in Fault state caused by {exception.Message}", exception);
 
            switch (exception)
            {
                case ServerException serverException:
                    return SillyResources.Error_Business;
                case NetworkException networkException:
                    return SillyResources.Error_Network;
                default:
                    return SillyResources.Error_Unknown;
            }
        }
```

There is also a diagnostic internal logger that you can activate with:

```SharpnadoInitializer.Initialize(enableInternalLogger: true);```

**Comment by alexrysgspr** [comment]
Just one question about TaskCompletionSource.

What happens if you don't set result on TaskCompletionSource but you return the Task? Is there any complications here?

Ex:
<code>
public static Task<string> GetInput(string input)
{
            var tcs = new TaskCompletionSource<string>();
            if (!string.IsNullOrEmpty(input))
                tcs.TrySetResult(input); 

            return tcs.Task;
}
</code>
