### ISSUE TITLE
Tiles overlapping on Nexus5X

### ISSUE THREAD

**Issue by 07vij1987** [roubachof/Sharpnado.Presentation.Forms#21]
**Platform (please complete the following information):**
 - OS: [Android]
 - Device: [AndroidEmulator - nexus5X]

**Describe the bug**
I have used the exactly same Grid layout that is used in SillyCompany.Mobile.Practices (View - SortSillyPeoplePage). And this is my landing page. ItemSource for it contains six elements. 

When page loads for the first time, I get 3 rows and 2 column for each row. However, these two columns are overlapped. It works fine once I drag and drop a cell.

Gone through the code of both SillyCompany and Sharpnado.Presentation.Forms, but not able to find the root cause.

attached the emulator screen for your reference.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/43951338/51823029-1626e580-2304-11e9-8451-1e4ddf6ff508.png)

**Comment by roubachof** [comment]
Sorry I can't replicate this.
I will need a repro sample and also:

**Comment by 07vij1987** [comment]
Below is the XAML. I have not used any other custom setting.

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:renderedViews="clr-namespace:Sharpnado.Presentation.Forms.RenderedViews;assembly=Sharpnado.Presentation.Forms"
             x:Class="DraGnDroP.Views.Home"
            >
    <ContentPage.Resources>
        <ResourceDictionary>
            <x:Double x:Key="SmallPadding">4</x:Double>
            <x:Double x:Key="MediumPadding">8</x:Double>
            <x:Double x:Key="StandardPadding">16</x:Double>
            <x:Double x:Key="TextSizeSmallCaption">11</x:Double>
            <x:Double x:Key="TextSizeCaption">12</x:Double>
            <Color x:Key="TextPrimaryColor">#B0000000</Color>
            <Thickness x:Key="MediumTopThickness" Top="{StaticResource MediumPadding}" />
            <Thickness x:Key="StandardThickness"
                       Bottom="{StaticResource StandardPadding}"
                       Left="{StaticResource StandardPadding}"
                       Right="{StaticResource StandardPadding}"
                       Top="{StaticResource StandardPadding}" />
            <OnPlatform x:Key="FontRegular" x:TypeArguments="x:String">
                <On Platform="iOS">OpenSans-Regular</On>
            </OnPlatform>
            <Style x:Key="TextCaption" TargetType="Label">
                <Setter Property="FontFamily" Value="{StaticResource FontRegular}" />
                <Setter Property="TextColor" Value="{StaticResource TextPrimaryColor}" />
                <Setter Property="FontSize" Value="{StaticResource TextSizeCaption}" />
            </Style>
            <Style x:Key="TextSmallCaption"
                   BasedOn="{StaticResource TextCaption}"
                   TargetType="Label">
                <Setter Property="FontSize" Value="{StaticResource TextSizeSmallCaption}" />
            </Style>
            <Style x:Key="SmallAvatar"
                   ApplyToDerivedTypes="True"
                   TargetType="Image">
                <Setter Property="HorizontalOptions" Value="Center" />
                <Setter Property="VerticalOptions" Value="Center" />
                <Setter Property="HeightRequest" Value="50" />
                <Setter Property="WidthRequest" Value="50" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>
    <ContentPage.Content>
        <StackLayout VerticalOptions="StartAndExpand">
            <StackLayout HeightRequest="200">
                <Image Source="">
                </Image>
            </StackLayout>
            <ScrollView>
            <renderedViews:HorizontalListView  ItemHeight="120"
                                               ItemWidth="110"
                                               ItemSpacing="8"
                                               CollectionPadding="8"
                                               EnableDragAndDrop="True"           
                                               ItemsSource="{Binding ScreenList}"
                                               ListLayout="Grid"
                                               x:Name="_hListView">
                <renderedViews:HorizontalListView.ItemTemplate>
                    <DataTemplate>
                        <renderedViews:DraggableViewCell x:Name="DraggableViewCell">
                            <ContentView>
                                <renderedViews:MaterialFrame Margin="4" 
                                                             Padding="{StaticResource StandardThickness}" 
                                                             Elevation="4">
                                    <Frame.Triggers>
                                        <DataTrigger Binding="{Binding Source={x:Reference DraggableViewCell}, Path=IsDragAndDropping}"
                                                     TargetType="renderedViews:MaterialFrame" Value="True">
                                            <Setter Property="Elevation" Value="8" />
                                        </DataTrigger>
                                    </Frame.Triggers>

                                    <Grid ColumnSpacing="0" RowSpacing="0">
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="2*" />
                                            <RowDefinition Height="*" />
                                                <RowDefinition Height="*" />
                                            </Grid.RowDefinitions>
                                            <Image Grid.Row="0"  Style="{StaticResource SmallAvatar}" Aspect="AspectFill" Source="{Binding ScreenURL}"></Image>
                                        <Label Grid.Row="1" Margin="{StaticResource MediumTopThickness}" 
                                               Style="{StaticResource TextSmallCaption}" 
                                               HorizontalTextAlignment="Center" 
                                               Text="{Binding ScreenName}" />
                                            <Label Grid.Row="2"
                                           Margin="{StaticResource MediumTopThickness}"
                                           Style="{StaticResource TextSmallCaption}"
                                           HorizontalTextAlignment="Center"
                                           Text="More Summary Info" />
                                        </Grid>
                                </renderedViews:MaterialFrame>
                            </ContentView>
                        </renderedViews:DraggableViewCell>
                    </DataTemplate>
                </renderedViews:HorizontalListView.ItemTemplate>
            </renderedViews:HorizontalListView>
            </ScrollView>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>

**Comment by 07vij1987** [comment]
Android sdk tools - 26.1.1
Android SDK platform - 27
Android 8.1 Oreo 
Xamarin.Forms version - 3.4.0.1029999

**Comment by 07vij1987** [comment]
Also, if I use ColumnCount property, it loads well. However, it shows only first row. I need to scroll for viewing other rows.


![image](https://user-images.githubusercontent.com/43951338/51845490-a2093380-233d-11e9-9bf7-fc51dd48bf85.png)

**Comment by roubachof** [comment]
Sorry for the misunderstanding but I need the whole solution not just the xaml.

**Comment by 07vij1987** [comment]
Hi
I have added the complete code.

[DraGnDrop.zip](https://github.com/roubachof/Sharpnado.Presentation.Forms/files/2807972/DraGnDrop.zip)

**Comment by 07vij1987** [comment]
Hi
I have found a work around for it. I am setting itemwidth and itemspacing dynamically now. It is working as expected.

I would like to thank you for developing this plugin. 
I was trying to build the same functionality over last 2 weeks without getting expected result. This plugin has saved my life.

Keep up the good work.

**Comment by roubachof** [comment]
Hi man,

I just wanted to share some piece of code that could be useful to most of Xamarin Forms developers.
I surely wouldn't expect to save people life by doing that :)
I will still have a look at your repro sample cause it could impact others as well.

**Comment by roubachof** [comment]
I really tried to run it, but I have an android resource error on the theme...
Anyway your layout is not really "standard" :)
You shouldn't put a HorizontalListView in Grid mode (meaning vertical scroll), in another Scrollview...

**Comment by 07vij1987** [comment]
If I don't use Scroll view, vertical scroll does not come up automatically

**Comment by roubachof** [comment]
Well there is definitely an issue with your layout then.
I will advise you to restart your screen from scratch, more grid and less stack layout :)

**Comment by 07vij1987** [comment]
yes, you were absolutely right :) 
Removed stack & scroll view, and used grid. It is working as expected now. 
Thanks a lot.
