### ISSUE TITLE
Adding items to HorizontalListView ItemSource adds extra space in Android

### ISSUE THREAD

**Issue by iamlawrencev** [roubachof/Sharpnado.Presentation.Forms#22]
**Platform:**
 - OS: Android
 - Device: Samsung Galaxy S6
 - SDK Version: Android 7.0
 - Xamarin.Forms: 3.4.0.1029999

**Describe the bug**

When adding items to the HorizontalListView's ItemSource in iOS, it fades the item in and has the same spacing as all the other elements in the collection. 

In Android it does not fade the item in and instead adds it outside the viewport then it has an uneven space in between but when it is swiped to the left outside the viewport, the spacing becomes even and correct when you swipe it back into view.

**To Reproduce**
1. Add a range to an ObservableRangeCollection bound to the HorizontalListView's ItemSource property when you are at the last element.

**Screen Capture**

iOS Behavior: https://i.imgur.com/xbk81Jt.gifv
Android Behavior: https://i.imgur.com/4AJLZtv.gifv

**Comment by roubachof** [comment]
Hi Lawrence!

Thanks for the videos :)
Also, can you give me the repro sample on android ?
Or at least the xaml code of the HorizontalListView ?

**Comment by iamlawrencev** [comment]
Thanks for the prompt reply!

Here is the XAML:

```
<renderedViews:HorizontalListView VerticalOptions="FillAndExpand"
                                  HorizontalOptions="FillAndExpand"
                                  BackgroundColor="{StaticResource PrimaryColor}"
                                  ItemSpacing="20"
                                  ColumnCount="1"
                                  ItemsSource="{Binding Items}"
                                  SnapStyle="Center"
                                  CurrentIndex="{Binding CurrentIndexValue}">
        <renderedViews:HorizontalListView.CollectionPadding>
            <OnPlatform x:TypeArguments="Thickness">
                <On Platform="iOS" Value="40, 65, 40, 45"/>
                <On Platform="Android" Value="40, 45"/>
            </OnPlatform>
        </renderedViews:HorizontalListView.CollectionPadding>

        <renderedViews:HorizontalListView.ItemTemplate>
            <DataTemplate>
                <ViewCell>
                    <Frame BackgroundColor="#4dd0e1"
                           CornerRadius="10"
                           Padding="0">
                        <Frame.IsClippedToBounds>
                            <OnPlatform x:TypeArguments="x:Boolean">
                                <On Platform="iOS" Value="true"/>
                            </OnPlatform>
                        </Frame.IsClippedToBounds>
                        <Grid effects:TapCommandEffect.Tap="{Binding Source={x:Reference page}, Path=BindingContext.ItemTappedCommand}"
                              effects:TapCommandEffect.TapParameter="{Binding .}"
                              effects:ViewEffect.TouchFeedbackColor="#212121">
                            <StackLayout VerticalOptions="End"
                                         Padding="20">
                                <Label Text="{Binding TestData}" FontSize="{StaticResource FontSizeExtraLarge}" FontAttributes="Bold" TextColor="White"/>
                                <Label Text="{Binding TestData}" TextColor="White"/>
                                <Label Text="{Binding TestData}" FontAttributes="Bold" TextColor="White"/>
                            </StackLayout>
                        </Grid>
                    </Frame>
                </ViewCell>
            </DataTemplate>
        </renderedViews:HorizontalListView.ItemTemplate>
</renderedViews:HorizontalListView>   
```

I'm just adding a range to the Items ObservableRangeCollection using `Items.AddRange(data)` in the ViewModel whenever the CurrentIndex is the last.

**Comment by iamlawrencev** [comment]
Hi @roubachof any update on this? Need any more samples, etc.? Thanks! :)

**Comment by roubachof** [comment]
Hi! 
I have reproduced the issue. I even thought I fixed it (I forgot to call InvalidateDecorations() on the RecyclerView when modifying the collection). Unfortunately it causes a weird behavior. So I am still working on it.

**Comment by roubachof** [comment]
Should be resolved by 0.9.10.

**Comment by iamlawrencev** [comment]
Thanks for fixing the issue @roubachof. There is a minor UI issue with the fix though which appears only on Android. The item now appears inside the viewport but does not seem to follow the `CollectionPadding` property of the `HorizontalListView`. In my case it appears next to the last item but has a smaller padding than the `CollectionPadding`. 

After it goes out of view with a swipe to the left it gets the right padding when brought back to view as has happened before.

**Comment by roubachof** [comment]
@iamlawrencev I created #26 as it is a new issue
