### ISSUE TITLE
ScrollTo Function

### ISSUE THREAD

**Issue by nicholaszanardi97** [roubachof/Sharpnado.Presentation.Forms#23]
Is it currently possible to perform an automatic scroll in the HorizontalListView programmatically up to the defined element?

If it has not yet been implemented it would be a useful feature.

Thank you

**Comment by roubachof** [comment]
yup, it is.
Just set the ```CurrentIndex``` property, I would recommend ```OneWay``` ```BindingMode``` if you don't care about being notified back.

**Comment by RockyBalboa2018** [comment]
works like a charm, but would be great with transitation/animation
Thank you
