### ISSUE TITLE
Views are not visible without scrolling away and back again.

### ISSUE THREAD

**Issue by LeoJHarris** [roubachof/Sharpnado.Presentation.Forms#25]
**Platform (please complete the following information):**
 - OS: Untested
 - Device: Android device
 - Sdk target version: 28
 - Xamarin.Forms: 3.5

Just noticed after updating Xamarin Forms to 3.5 that when the horizontal list view is first shown no items are appearing, its only when I slide along and then back again that items actually begin appearing.

My code seems to be unchanged from when it was working.

**Comment by roubachof** [comment]
sadly reproduced x)

**Comment by roubachof** [comment]
Should be resolved by 0.9.10

**Comment by osmansurv** [comment]
Another note here, my requirement was to have the HorizontalListView with a header. I just tried with 0.9.8 version and I could simply put the HorizontalListLayout with custom header content view in a StackLayout as children and everything all together in ScrollView with DisableScroll set to true for the HorizontalListView. It works and I can scroll up and down but then there is this issue with views being not visible. I updated to 0.9.10 but then I lost the ability to scroll up and down. Is it possible to get this back like it was in 0.9.8?

**Comment by roubachof** [comment]
@osmansurv nested scrollviews are not supported. If you want custom header you can totally achieve that with template selector: https://docs.microsoft.com/en-US/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector.

**Comment by LeoJHarris** [comment]
Hi @roubachof Doesn't seem to be resolved in 0.9.10 using latest xamarin forms 3.5.0.129452

**Comment by roubachof** [comment]
Sorry I cannot reproduce. I would need a repro sample.

**Comment by LeoJHarris** [comment]
Well upon stripping out much of my code to provide a sample project for you the issue was gone, so I guess there is something in my code that maybe affecting it, however rolling back to Xamarin forms 3.4 does fix the issue.

**Comment by roubachof** [comment]
mmh don't like those weird bugs....

**Comment by LeoJHarris** [comment]
Seems to be working now actually, the cell item was an image using CachedImage plugin and using Xamarin Forms 3.5 and setting width and height resolves the issue. Where as previously not setting a height and width of the image was fine.

**Comment by LeoJHarris** [comment]
I also had some text which was actually showing in the sample repo as well but the image wasnt showing so still thought it might still been related to this plugin.

**Comment by LeoJHarris** [comment]
Will close issue
