### ISSUE TITLE
ItemSpacing not accurate when adding item to the end

### ISSUE THREAD

**Issue by roubachof** [roubachof/Sharpnado.Presentation.Forms#26]
**Platform**
* OS: Android
* Device: Samsung Galaxy S6
* SDK Version: Android 7.0
* Xamarin.Forms: 3.4.0.1029999

**Describe the bug**
The item now appears inside the viewport but does not seem to follow the `ItemSpacing` property of the `HorizontalListView`. In my case it appears next to the last item but has a smaller padding than the `ItemSpacing`.

After it goes out of view with a swipe to the left it gets the right spacing when brought back to view as has happened before.

**Comment by roubachof** [comment]
@iamlawrencev sadly I didn't reproduce your issue.

![infinite loading](https://user-images.githubusercontent.com/596903/52642298-064dfa80-2edb-11e9-98a7-4ca5334167e2.gif)

**Comment by iamlawrencev** [comment]
I'll send a reproducible solution in a short while @roubachof. Thanks!

**Comment by roubachof** [comment]
some news about his one ?

**Comment by iamlawrencev** [comment]
I've tried reproducing it now but I can't anymore. I've tested it on 0.9.11 and it's fixed now. Thanks @roubachof. :)

**Comment by roubachof** [comment]
\o/  thanks for reporting the initial issue :)
