### ISSUE TITLE
How do i update the order of items in list view while dragging and dropping the items?

### ISSUE THREAD

**Issue by SatyaRamprasad** [roubachof/Sharpnado.Presentation.Forms#28]
How do i update the order of items in list view while dragging and dropping the items? Is there any event for order change?

**Comment by roubachof** [comment]
```DragAndDropEndedCommandProperty```

**Comment by SatyaRamprasad** [comment]
Hi @roubachof ,

Thanks for the reply. I will look in to it and get back to you.

**Comment by SatyaRamprasad** [comment]
@roubachof command is firing, but how to pass dragged item data from view to view model?

**Comment by roubachof** [comment]
Items ViewModels are synced with your ItemsSource

**Comment by SatyaRamprasad** [comment]
@roubachof  But i need to update the order in the items source too

**Comment by 07vij1987** [comment]
@roubachof  - I have found an issue with DragAndDropEndedCommand.
On calling this command it, changes in the Item (on view model) (Bind to itemsource with Two way mode) are not reflected immediately.  
Changes are visible only after I navigate to other page.

**Comment by NickeManarin** [comment]
@roubachof The `DragAndDropEndedCommand` is called before the list is reordered. Is there any reliable way to know when the list was reordered?

There's an event called `ChildrenReordered`  too but it never fires.

I'm using an `ObservableCollection<Object>` as my backing property for the `ItemsSource` of the `HorizontalListView` element.
