### ISSUE TITLE
Guard exception is raised whereas ItemWidth is not set by the user

### ISSUE THREAD

**Issue by ahmed-sherien** [roubachof/Sharpnado.Presentation.Forms#30]
**Platform (please complete the following information):**
 - OS: Android
 - Device: Wiko / AndroidEmulator
 - Sdk vervion: Android 8.1
 - Xamarin.Forms: [3.4.0.1029999]

**Describe the bug**
When I try to load the page back using frame navigation service the app crashes.
 
Frame Navigation Service:
```
private MainPage _mainPage = (MainPage)App.Current.MainPage;
readonly Dictionary<PageType, NavigationPage> MenuPages = new Dictionary<PageType, NavigationPage>();
readonly Stack<KeyValuePair<PageType, NavigationPage>> History = new Stack<KeyValuePair<PageType, NavigationPage>>();

public async Task NavigateTo(PageType pageType)
{
    if (!MenuPages.ContainsKey(pageType)) return;
    await ProcessNavigation(pageType, () => MenuPages[pageType]);
}

public async Task Back()
{
    var page = History.Pop().Value;
    await _mainPage.NavigateTo(page);
}

private async Task ProcessNavigation(PageType pageType, Func<NavigationPage> func)
{
    History.Push(new KeyValuePair<PageType, NavigationPage>(_mainPage.CurrentPageType, (NavigationPage)_mainPage.Detail));
    var page = func();
    _mainPage.CurrentPageType = pageType;
    await _mainPage.NavigateTo(page);
}
```

HorizontalListView:
```
<sharpnado:HorizontalListView ItemsSource="{Binding Media}" ListLayout="Carousel" HeightRequest="150" IsVisible="{Binding HasMedia}">
    <sharpnado:HorizontalListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <sharpnado:MaterialFrame VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand">
                    <Grid>
                        <Image Source="{Binding ImageURL}" Aspect="AspectFill" />
                        <ImageButton Source="play_arrow.png" Aspect="AspectFit" HorizontalOptions="Center" VerticalOptions="Center"
                        WidthRequest="50" HeightRequest="50" IsVisible="{Binding IsVideo}" BackgroundColor="Transparent"
                        Command="{Binding Path=BindingContext.OpenLinkCommand, Source={x:Reference Name=ItemsListView}}"
                        CommandParameter="{Binding MediaURL}"/>
                    </Grid>
                </sharpnado:MaterialFrame>
            </ViewCell>
        </DataTemplate>
    </sharpnado:HorizontalListView.ItemTemplate>
</sharpnado:HorizontalListView>
```

**To Reproduce**
1. Create a Frame Navigation Service, a Page with HorizontalListView (HLV), and a Page to navigate to and from 
2. Load HLV Page
3. Navigate to other page and back

**Exceptions (if applicable)**

```
System.InvalidOperationException: 
You cannot set at the same time the item width and the column count: 
ItemWidth will be automatically calculated from padding and margin to fit in the number of columns specified
```

**Comment by roubachof** [comment]
I beed the xaml of the ```HorizontalListView```

**Comment by ahmed-sherien** [comment]
@roubachof I updated it ...

**Comment by JJEEGG2211** [comment]
I think I have a similar issue. I get the following exception:

**Comment by ahmed-sherien** [comment]
any news or workarounds for this issue?

**Comment by heiser** [comment]
I'm also encountering this issue

**Comment by roubachof** [comment]
will fix this at the end of the week

**Comment by ahmed-sherien** [comment]
Hey @roubachof, when it will be available on Nuget ?

**Comment by roubachof** [comment]
probably today :)

**Comment by roubachof** [comment]
fingers crossed: https://github.com/roubachof/Sharpnado.Presentation.Forms/releases/tag/v0.9.11

**Comment by ahmed-sherien** [comment]
![image](https://user-images.githubusercontent.com/2738620/53814076-a261a380-3f67-11e9-8111-bbfdd221ab51.png)

**Comment by roubachof** [comment]
Ok well this is what happen when nobody gives me a repro sample: a shoot in a dark...

**Comment by ahmed-sherien** [comment]
okay let's get this [sample](https://github.com/ahmed-sherien/Sharpnado.HLV.Issue) work first ... it throws null reference exception when I'm loading the page

**Comment by roubachof** [comment]
Thanks man, I appreciate.

**Comment by ahmed-sherien** [comment]
@roubachof any news?

**Comment by roubachof** [comment]
well...

> IMPORTANT: On platform projects, call SharpnadoInitializer.Initialize() after Xamarin.Forms.Forms.Init() and before LoadApplication(new App()).

:)

Do you have a repro sample for Guard exception issue ?

**Comment by ahmed-sherien** [comment]
Oh ... my bad ... I'll work on the same repo to reproduce the issue

**Comment by ahmed-sherien** [comment]
done it is reproducing now

**Comment by roubachof** [comment]
Great! I will have a look tomorrow

**Comment by roubachof** [comment]
ok it will be fixed in the next release :)

**Comment by ahmed-sherien** [comment]
Great thanks ... any definite date/time ?

**Comment by roubachof** [comment]
I'm waiting for the guys of issue #29 to answer...

**Comment by ahmed-sherien** [comment]
> I'm waiting for the guys of issue #29 to answer...

any news ?

you know if you can post this fix it will be great as I'm a bit stuck and running out of time now and I would really appreciate your help ... Thanks

**Comment by roubachof** [comment]
v0.9.12 has been uploaded to nuget!

**Comment by ahmed-sherien** [comment]
Thanks for your efforts, issue fixed ...
