### ISSUE TITLE
DragAndDropEndedCommand - changes to view model not reflected immediately

### ISSUE THREAD

**Issue by 07vij1987** [roubachof/Sharpnado.Presentation.Forms#31]
@roubachof - I have found an issue with DragAndDropEndedCommand.
On calling this command it, changes in the Item (on view model) (Bind to itemsource with Two way mode) are not reflected immediately.
Changes are visible only after I navigate to other page.

**Comment by roubachof** [comment]
sorry I'm afraid I don't understand your issue

**Comment by 07vij1987** [comment]
Ok, I will explain it. I have a public  List<T> property namely screenlist in my view model which is itemsource for horizontal list view with grid layout. 
After rearranging cells DragAndDropEndedCommand is invoked. I expect changes to reflect in the screenlist property when this command is invoked. But it not done.  Only after I move to some other page and then come back to this page, screenlist property is updated.

**Comment by roubachof** [comment]
Well if it's not an ObservableCollection it won't work... Please look at the silly app.

**Comment by 07vij1987** [comment]
Yes, it is not an ObservableCollection. Though I have implemented INotifyPropertyChanged for the list.

I will change it to ObservableCollection and revert once done.
Thank you.

**Comment by srinu213** [comment]
Required proper example to DragandDropcommand by passing paramenters
