### ISSUE TITLE
DragAndDropEndedCommand is not firing in IOS

### ISSUE THREAD

**Issue by 07vij1987** [roubachof/Sharpnado.Presentation.Forms#32]
Hi @roubachof 

DragAndDropEndedCommand is not firing in IOS - checked on 4-5 IOS devices. It works on android though. 

Version - 0.9.9

HorizontalListView XAML code
            <renderedViews:HorizontalListView
                                               ItemHeight="130"                                            
                                               EnableDragAndDrop="True"           
                                               ItemsSource="{Binding ScreenList , Mode=TwoWay}"
                                               ListLayout="Grid"
                                               x:Name="_hListView"
                                               CollectionPadding="0"
                                               ItemSpacing="0"
                                               Grid.Row="1" Grid.Column="0"
                                               DragAndDropEndedCommand="{Binding Path=BindingContext.SavePreferences,Source={x:Reference Name= MyView}}">

ViewModel code : 

namespace MyMobileApp.ViewModels
{
    public class MyViewModel : NavigableViewModel
    {
public MyViewModel(INavigation _navigation)
        {
            Navigation = _navigation;
            savePreferences = new Command(OnDragNDropEnd);
        }

  ICommand savePreferences;
 public ICommand SavePreferences
        {
            get { return savePreferences; }
        }

        private void OnDragNDropEnd()
        {
            AppStaticDetails.dragAndDropped = true;
        }
}
}

View Code

public partial class Home : ContentPage
    {
        short Counter = 0;
        int SlidePosition = 0;

        MyViewModel viewModel = null;
        public Home()
        {
            InitializeComponent();
            viewModel = new MyViewModel(Navigation);
            this.BindingContext = viewModel;
        }
}

**Comment by roubachof** [comment]
it works on 0.9.11 :)

**Comment by 07vij1987** [comment]
Okay
Will try it tomorrow :)

**Comment by shawyunz** [comment]
Just a reminder for others have same mistakes, remember to use "DraggableViewCell" instead of the default ViewCell. As ViewCell goes fine on Android and failed in ios.
[check the renderer condition hereh](https://github.com/roubachof/Sharpnado.Presentation.Forms/blob/master/Sharpnado.Presentation.Forms.iOS/Renderers/HorizontalList/iOSHorizontalListViewRenderer.DragAndDrop.cs#L102-L106).
