### ISSUE TITLE
Scroll programmatically on needed element

### ISSUE THREAD

**Issue by CutestFox** [roubachof/Sharpnado.Presentation.Forms#33]
**Platform (please complete the following information):**
 - OS: [iOS]
 - Device: [iPhone7]
 - Sdk vervion: [iOS 12.1.4]
 - Xamarin.Forms: [3.4.0.1029999]

**Describe the bug**
Im trying to set CurrentIndex property on HorizontalListView on OnAppearing to scroll to element. It works on android, but not on ios.

**To Reproduce**
1. In code behind of page set horisontalListView.CurrentIndex

**Exceptions (if applicable)**
How can i scroll on needed list item on both platforms?
```

**Comment by roubachof** [comment]
Sorry man but I just tested the silly app with:

1. Binding ```CurrentIndex``` to a view model property
2. Setting ```CurrentIndex``` in the view's constructor
3. Setting ```CurrentIndex``` in the ```OnAppearing``` of the view

It works on all cases on iOS.

```csharp
namespace SillyCompany.Mobile.Practices.Presentation.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class SillyInfinitePeoplePage : ContentPage, IBindablePage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SillyPeoplePage"/> class.
        /// </summary>
        public SillyInfinitePeoplePage()
        {
            InitializeComponent();

            TaskLoaderHeader.Height = SizeScalingByScreenConverter.Instance.Convert(TaskLoaderHeader.Height.Value);
            SillyOfTheDayHeader.Height = SizeScalingByScreenConverter.Instance.Convert(SillyOfTheDayHeader.Height.Value);
            ListViewHeader.Height = SizeScalingByScreenConverter.Instance.Convert(ListViewHeader.Height.Value);
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            HorizontalListView.CurrentIndex = new Random().Next(9);
        }
    }
}
```

**Comment by CutestFox** [comment]
When Im trying to set binding to a view model property it doesn't work too

```XAML
<sharpnado:HorizontalListView ItemHeight="55" ItemWidth="55" ItemsSource="{Binding Items}" CurrentIndex="{Binding CurrentItemIndex}"
                                          VerticalOptions="End" Margin="2,0,2,7" CollectionPadding="20,20,20,0" >
                <sharpnado:HorizontalListView.ItemTemplate>
                    <DataTemplate>
                        <cells:ChosableViewCell />
                    </DataTemplate>
                </sharpnado:HorizontalListView.ItemTemplate>
            </sharpnado:HorizontalListView> 
``` 

Only Android

**Comment by roubachof** [comment]
Sorry can't reproduce... Please try the silly app, you will see it's working and we'll have a working example.

**Comment by pandyabrijesh** [comment]
@CutestFox 
I was also having same problem. i fixed by adding this line into XAML.
In my HorizontalListView this property set to SnapStyle="None" before and i have modified to SnapStyle="Center".

As @roubachof suggested I have checked that in silly app and found only difference was that above mentioned line (property).

**Comment by Mitke2011** [comment]
@pandyabrijesh for a short delay did the trick, in combination what you've done with SnapStyle.
Task.Delay(100);
myHorizontalListView.CurrentIndex = new Random().Next(9);
