### ISSUE TITLE
Get Updated List from Dragable List

### ISSUE THREAD

**Issue by viveklpu2011** [roubachof/Sharpnado.Presentation.Forms#36]
How to get updated list when drag the items from one place to another in horizontal list view

**Comment by roubachof** [comment]
same as #31, use ObservableCollection. See the Silly app example.

**Comment by viveklpu2011** [comment]
where is the Silly App example. Please provide the link.

**Comment by roubachof** [comment]
from readme.md: "Those components are used and tested in the Silly! app: https://github.com/roubachof/Xamarin-Forms-Practices."

**Comment by viveklpu2011** [comment]
thanks

**Comment by viveklpu2011** [comment]
@roubachof  i have gone through the code and it is working but i  found that when i drag and drop item from one place to another it is giving the the previous updated list, not the current.
may be i am not doing in a correct way, please suggest.

 I used OnDragAndDropEndCommand command to get the current updated list after drag and drop
