### ISSUE TITLE
Some Samsung devices - AndroidHorizontalListViewRenderer.OnLayout - java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0

### ISSUE THREAD

**Issue by TheWraithL98** [roubachof/Sharpnado.Presentation.Forms#39]
This seems like a really common issue with RecyclerView usage - there are a ton of articles out there on fixing it.  One example is here:  https://readyandroid.wordpress.com/java-lang-indexoutofboundsexception-inconsistency-detected-invalid-item-position-android-recyclerview/

JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
ViewGroup.Layout (System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b)
ViewRenderer`2[TView,TNativeView].OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b)
AndroidHorizontalListViewRenderer.OnLayout (System.Boolean changed, System.Int32 left, System.Int32 top, System.Int32 right, System.Int32 bottom)
FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4)
(wrapper dynamic-method) System.Object.37(intptr,intptr,bool,int,int,int,int)
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:3).state:3 md54d4a5cd7b1153e9de4a2e3782bf80f5b.SlowRecyclerView{1a601a7 VFED..... ......I. 0,0-1384,1254 #18}, adapter:md54d4a5cd7b1153e9de4a2e3782bf80f5b.AndroidHorizontalListViewRenderer_RecycleViewAdapter@28285c6, layout:md54d4a5cd7b1153e9de4a2e3782bf80f5b.CustomLinearLayoutManager@79f39fd, context:md53bdc57950d72e4c7642aabd501f118ca.MainActivity@4fbe6eb
android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5654)
android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3434)
android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
md54d4a5cd7b1153e9de4a2e3782bf80f5b.AndroidHorizontalListViewRenderer.n_onLayout(Native Method)
md54d4a5cd7b1153e9de4a2e3782bf80f5b.AndroidHorizontalListViewRenderer.onLayout(AndroidHorizontalListViewRenderer.java:45)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onLayout(Native Method)
md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onLayout(NavigationPageRenderer.java:65)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md51558244f76c53b6aeda52c8a337f2c37.PageContainer.n_onLayout(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.PageContainer.onLayout(PageContainer.java:46)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
md515a6121043c3ea2ce109e48dc25d933d.BottomBarPageRenderer.n_onLayout(Native Method)
md515a6121043c3ea2ce109e48dc25d933d.BottomBarPageRenderer.onLayout(BottomBarPageRenderer.java:47)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.n_onLayout(Native Method)
md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.onLayout(PlatformRenderer.java:55)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
android.widget.FrameLayout.onLayout(FrameLayout.java:261)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
android.widget.FrameLayout.onLayout(FrameLayout.java:261)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
android.widget.FrameLayout.onLayout(FrameLayout.java:261)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
android.widget.FrameLayout.onLayout(FrameLayout.java:261)
com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
android.view.View.layout(View.java:20854)
android.view.ViewGroup.layout(ViewGroup.java:6401)
android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2956)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2643)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
android.view.Choreographer.doCallbacks(Choreographer.java:723)
android.view.Choreographer.doFrame(Choreographer.java:658)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
android.os.Handler.handleCallback(Handler.java:789)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6944)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by roubachof** [comment]
Great! Then you can test if it solves your issue, and make a PR!
(You didn't see that one coming did you x)

**Comment by TheWraithL98** [comment]
I'm going to close this for now - I can't reliable reproduce it - I'm getting logged errors through App Center reports sporadically, but I can't reproduce on my 3 Android test devices.  If I can come up with quality repro steps I will reopen/reenter and I will enter a PR.

**Comment by roubachof** [comment]
nope. If you see crashes on app center, it needs to be addressed.

**Comment by TheWraithL98** [comment]
I'm ok with you leaving it open, but I can't currently go any further without reproducing, or I can't verify effectiveness of any fix.

**Comment by roubachof** [comment]
np. I will try some things before next release :)

**Comment by AlexTeixeira** [comment]
Hi,

Currently I have the same issue with a Samsung Galaxy S7 with Android 7.0 and S10 with Android 9.0.
Application crash when I use the Horizontal list view.

```
    AndroidHorizontalListViewRenderer+OnControlScrollChangedListener.UpdateCurrentIndex (Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.AndroidHorizontalListViewRenderer nativeView, System.Threading.CancellationToken token)
    AndroidHorizontalListViewRenderer+OnControlScrollChangedListener.OnScrollStateChanged (Android.Support.V7.Widget.RecyclerView recyclerView, System.Int32 newState)
    RecyclerView+OnScrollListener.n_OnScrollStateChanged_Landroid_support_v7_widget_RecyclerView_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_recyclerView, System.Int32 newState)
    (wrapper dynamic-method) System.Object.116(intptr,intptr,intptr,int)
```

**Comment by roubachof** [comment]
@AlexTeixeira what makes you think it's the same issue ?
Could you provide the full exception stack ?

**Comment by AlexTeixeira** [comment]
@roubachof I get the full exception stack in android ( I have nothing better in app center ). And is not the same issue.

I will open a new one. Sorry

**Comment by roubachof** [comment]
@TheWraithL98 I added some code in the android renderer. We'll see if it works :)
