### ISSUE TITLE
Using TaskLoaderView in code behind

### ISSUE THREAD

**Issue by OKameric** [roubachof/Sharpnado.Presentation.Forms#4]
I tried your example and it works when I make a simple project and use XAML for views and bindings. But when I try to create the UI without XAML there is no loading indicator for the view that is wrapped in TaskLoaderView and it's visible all the time even though the task running in ViewModelLoader<object> property in corresponding VM of the page takes for example 10 seconds. 

Is there an additional step to make this possible when creating views and pages in the code?

Btw, awesome library!

**Comment by roubachof** [comment]
Can I have a code sample of your code behind and of your view model? I don’t see a reason why it shouldn’t work.

**Comment by OKameric** [comment]
You can check it here:
[https://github.com/OKameric/TaskLoaderViewExample](url)

It's just a quick example with 2 buttons. One is leading to XAML page and one to code behind page.  Both pages have same viewmodel.

**Comment by OKameric** [comment]
Oh great, it works now :)

Thank you for your time!
