### ISSUE TITLE
Extra space when change HorizontallListview HeightRequest

### ISSUE THREAD

**Issue by Giovannapls** [roubachof/Sharpnado.Presentation.Forms#40]
**Platform**
 - OS: Android
 - Device: Xiaomi Redmi S2
 - Sdk version: Android 8.1 (API level 27)
 - Xamarin.Forms: 3.6.0.220655

**Describe the bug**
Changing the HeightRequest causes a Extra space to appear when Drag And Drop Feature is used.

**To Reproduce**
1. Create a HorizontalListView
2. Change it HeightRequest
3. Try to Drag and Drop a Item.

**Screenshots**
Before Drag&Drop
![IMG_20190328_101853](https://user-images.githubusercontent.com/37786977/55160985-48f22c00-5143-11e9-9dc7-51436f4d2b7f.jpg)
After Drag&Drop
![IMG_20190328_101910](https://user-images.githubusercontent.com/37786977/55160988-4abbef80-5143-11e9-8ba9-61be19d3944d.jpg)

Might be related to [this Issue](https://github.com/roubachof/Sharpnado.Presentation.Forms/issues/26).

**Comment by roubachof** [comment]
I was waiting for this issue to be opened x)

**Comment by roubachof** [comment]
just fixed it!
will be in next release

**Comment by Giovannapls** [comment]
Nice! May I ask what was the problem?

**Comment by roubachof** [comment]
The custom item decorator was a real mess for the grid layout. I finally decided to clean it up.
The fix of this issue is a collateral damage x)

**Comment by roubachof** [comment]
fixed in https://github.com/roubachof/Sharpnado.Presentation.Forms/releases/tag/v1.1.0
