### ISSUE TITLE
Projects fail to load on Visual Studio for Mac

### ISSUE THREAD

**Issue by ali-h2010** [roubachof/Sharpnado.Presentation.Forms#42]
**Platform (please complete the following information):**
 - OS: Both
 - Device: All
 - Sdk vervion: All
 - Xamarin.Forms: Not related

**Describe the bug**
Multiple projects are not being loaded at the start up of Visual studio for mac. For some reason they are not being downloaded when i download this repo.

**To Reproduce**
1. Download the solution
2.Load the solution using visual studio for mac

**Comment by roubachof** [comment]
Please learn about git submodules: https://git-scm.com/book/en/v2/Git-Tools-Submodules
