### ISSUE TITLE
Is it possible to show piece of next item?

### ISSUE THREAD

**Issue by jocontacter** [roubachof/Sharpnado.Presentation.Forms#46]
**Is your feature request related to a problem? Please describe.**
I'm trying to show to user possibility of scrolling when HLW is in Carousel mode

**Describe the solution you'd like**
I want to show piece of the next item on the edge of screen next to current item

![image](https://user-images.githubusercontent.com/33810579/56498989-fff88200-650c-11e9-9ee3-27c500562b75.png)

**Comment by roubachof** [comment]
yes you can by having a horizontal CollectionPadding > ItemSpacing:

https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/Views/TabsLayout/ListView.xaml

**Comment by jocontacter** [comment]
> yes you can by having a horizontal CollectionPadding > ItemSpacing:

Is negative horisontal margin needed?

**Comment by roubachof** [comment]
Nope.

**Comment by jocontacter** [comment]
> Nope.

Thank you. It worked!
