### ISSUE TITLE
[Feature] Enable Tab visibility toggle

### ISSUE THREAD

**Issue by nielscup** [roubachof/Sharpnado.Presentation.Forms#47]
**Is your feature request related to a problem? Please describe.**
Binding UnderlinedTabItem visibility property results in the tabItem being hidden when false, but leaves an unused space visible.

**Describe the solution you'd like**
If I set an UnderlinedTabItem.Isvisible to false I would like the remaining tabitems to fill the space.

**Describe alternatives you've considered**
Add tabItems in code

**Comment by nielscup** [comment]
Added tabs in code doesn't work (so far): If I clear tabs and re-add them they are not connected to any view.

**Comment by nielscup** [comment]
**Reason: _tabs is not updated in OnChildRemoved.** 

So if I do TabViewHost.Children.Clear() and re-add my 3 tabs, there are 6 items in _tabs.

**Comment by wint100** [comment]
Did you find a workaround for this, I'm having the same problem. When removing tabitems in code, the remaining tabs don't fill the boxview.

**Comment by roubachof** [comment]
there is no workaround, the implementation needs to be changed.
I will work on that during august

**Comment by jemunk** [comment]
Well, I think I have a workaround that seems to work. 
For every TabItem added in XAML to the TabHostView view, a columndefinition is also added to the Grid that TabHostView is based on. 
So If you get the columndefinition for item to hide, then set Width to zero. Also to be sure that the tab is not accidentally activated, set its IsEnabled = false.

**Comment by roubachof** [comment]
I am actually working on this issue at this very moment :)
Soon you will have the choice between fixed tabs and scrollable tabs, and the IsVisible property will be fixed for any of the tab types.

**Comment by roubachof** [comment]
fixed in v1.3.0
