### ISSUE TITLE
Is there anyway to change the ListView SelectedItem background color on horizontal list control?

### ISSUE THREAD

**Issue by tomwalker-guestlogix** [roubachof/Sharpnado.Presentation.Forms#49]
Is there anyway to change ListView SelectedItem background color  horizontal list control? l

I tried this [sample](https://www.c-sharpcorner.com/article/how-to-change-listview-selecteditem-bg-color-in-xamarin-forms/)  and applied a custom renderer to the  horizontal list control.

```
[assembly: ExportRenderer(typeof(CustomViewCell), typeof(CustomViewCellRenderer))]
namespace xamformsdemo.iOS.CustomControls
{
    public class CustomViewCellRenderer : ViewCellRenderer
    {
        public override UITableViewCell GetCell(Cell item, UITableViewCell reusableCell, UITableView tv)
        {
            var cell = base.GetCell(item, reusableCell, tv);
            var view = item as CustomViewCell;
            cell.SelectedBackgroundView = new UIView
            {
                BackgroundColor = view.SelectedItemBackgroundColor.ToUIColor(),
            };

            return cell;
        }
```

**Comment by roubachof** [comment]
errr for now items cannot be selected just tapped with the TapCommandEffect. You can change the ripple effect color though.

```
                            <renderedViews:HorizontalListView.ItemTemplate>
                                <DataTemplate>
                                    <ViewCell>
                                        <views:SillySquareCell
                                            effects:TapCommandEffect.Tap="{Binding OnItemTappedCommand}"
                                            effects:TapCommandEffect.TapParameter="{Binding .}"
                                            effects:ViewEffect.TouchFeedbackColor="{StaticResource Accent}" />
                                    </ViewCell>
                                </DataTemplate>
                            </renderedViews:HorizontalListView.ItemTemplate>
```

**Comment by tomwalker-guestlogix** [comment]
Thx @roubachof,   I was able to use a IsSelected property on the viewmodel datasource.  I used the new property and converter to set the background color of the parent element within the viewcell.  I have to refresh the list each time to set the IsSelected property correctly.  The good thing is my dataset will always be less than 20 items.

**Comment by roubachof** [comment]
Well you could something with binding the Background property of your View to the IsSelected property of your view model and a ValueConverter converting a bool to a color

**Comment by tomwalker-guestlogix** [comment]
Good point,  I could just move the binding to the viewcell background property.
