### ISSUE TITLE
Task Loader not working properly with HorizontalListView

### ISSUE THREAD

**Issue by Giovannapls** [roubachof/Sharpnado.Presentation.Forms#51]
**Platform (please complete the following information):**
 -OS: Android
 -Device: Oneplus a5000
 -Sdk version: Android 9.0 
 -Xamarin.Forms: 3.6.0.220655

**Describe the bug**
HorizontalListView doesn't display items if using Task Loader.

**To Reproduce**
1. Create a HorizontalListView
2. Add a TaskLoaderView
3. See error

**Code**
```
`MyLoader = new          Sharpnado.Presentation.Forms.ViewModels.ViewModelLoader<ObservableCollection<RootObject>>(ApplicationExceptions.ToString,null); 

           
 private async void Teste()
        {
            MyLoader.Load(LoadAsync);
        }
```

        private async System.Threading.Tasks.Task<ObservableCollection<RootObject>> LoadAsync()
        {
            ClientHttpStruct clientHttp = new ClientHttpStruct();
            var a = await clientHttp.GetFromWebApi<List<RootObject>>("myAPIAdress");
            TestItems = new ObservableCollection<RootObject>(a);
            return TestItems;
        } `
**Screenshots (if applicable)**

**Loading[Appears on both Lists]**
![image](https://user-images.githubusercontent.com/37786977/56755425-e1d98e80-6765-11e9-9551-8344762ca757.png)

**Result after Loading [Normal ListView]:**
![image](https://user-images.githubusercontent.com/37786977/56755516-13eaf080-6766-11e9-9559-c2e9378cde17.png)

**Result after Loading [HorizontalListView]**
![image](https://user-images.githubusercontent.com/37786977/56755573-33821900-6766-11e9-9d78-efe5972a1de4.png)

I Already tried binding the MyLoader.Result instead of TestItems. Results are pretty much the same.

**Comment by roubachof** [comment]
xaml needed :)

**Comment by Giovannapls** [comment]
Sure!
```
<customViews:TaskLoaderView  ViewModelLoader="{Binding MyLoader}">
            <renderedviews:HorizontalListView ItemsSource="{Binding TestItems}"
                          ItemHeight="60">
                <renderedviews:HorizontalListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <StackLayout Margin="8">
                                <Label Text="{Binding Rota}"
                                       FontAttributes="Bold" />
                            </StackLayout>
                        </ViewCell>
                    </DataTemplate>
                </renderedviews:HorizontalListView.ItemTemplate>
            </renderedviews:HorizontalListView>
        </customViews:TaskLoaderView>
```

```
<customViews:TaskLoaderView  ViewModelLoader="{Binding MyLoader}">
            <ListView ItemsSource="{Binding TestItems}"                          
                          RowHeight="60">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <StackLayout Margin="8">
                                <Label Text="{Binding Rota}"
                                       FontAttributes="Bold" />
                            </StackLayout>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </customViews:TaskLoaderView> 
```

**Comment by roubachof** [comment]
you need to specify either:

1. The ItemWidth property
2. Or the ColumnCount property

**Comment by Giovannapls** [comment]
I'm having the same issue in another code where ColumnCount is specified. Anyway, i will try it tomorrow and see if it works.
Thanks!

**Comment by Giovannapls** [comment]
It works. I found out what I was doing wrong in my other code.
The xaml was:
```
<TaskLoaderView>
<StackLayout>
<MyList>

```
When it should be
```
<StackLayout>
<TaskLoaderView>
<MyList>
```
Thanks for your time and keep up with your awesome work!
