### ISSUE TITLE
not able to see full item

### ISSUE THREAD

**Issue by SagarPanwala** [roubachof/Sharpnado.Presentation.Forms#55]
**Platform (please complete the following information):**
 - OS: iOS
 - Device: iPhoneSimulator(All)
 - Sdk vervion: iOS 11,12
 - Xamarin.Forms: 4.0.0.425677, 3.5.0.274416 ,3.4.0.1029999

**Describe the bug**
- not able to scroll to see the all the items. Last item is not visible fully. I tried with different Xamarin Forms version too. But looks like bug is with Something else. In Android this works perfectly fine.

**To Reproduce**
1. try to scroll and access the items
2. See video

**Attachments **
Here is the video https://www.dropbox.com/s/odwrv1xxe9xfych/sharpendo%20iOS%20scroll%20issue.mov?dl=0

**Comment by roubachof** [comment]
Please learn to use the HorizontalListView with this app:

https://github.com/roubachof/Xamarin-Forms-Practices

Also, read the doc in the Readme.md of this project.

ty.

**Comment by SagarPanwala** [comment]
@roubachof : Can you please guide me what can be the problem of the bug? I'm using same thing in other project and I'm using same thing. I'm not asking that you send me full code, but what can be the issue , so I can take care next time and other developer can also know.
