### ISSUE TITLE
CachingStrategy for the HorizontalListView

### ISSUE THREAD

**Issue by Shaw6157** [roubachof/Sharpnado.Presentation.Forms#56]
[issues]
when I added data to list from the previous page for the first time, perfect.
when I click "back" on "navigation tool bar" (didnot override anything), and added again, error: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.SlowRecyclerView'.

[possible solution]
I checked online and found a possible solution mentioned that: set CachingStrategy to RecycleElement. (Link: https://forums.xamarin.com/discussion/80533/error-cannot-access-a-disposed-object)

However, I was unable to access the "CachingStrategy" for the HorizontalListView, is it a potential feature to work on? (btw, I'm new in Xamarin developer)

Cheers

**Comment by roubachof** [comment]
Hey man!

I don't think this have anything to do with the caching strategy.
The link you provide is about the ListView which has nothing to do with the HorizontalListView.
But if you have a complete exception stack, or better, a repro sample I will be happy to have a look :)

**Comment by Shaw6157** [comment]
Thanks for your reply and sorry about the wrong issue reporting.
It turned out the error came from the "ObservableCollection".
When the page binding the collection pops, the app cannot access to that list again.
Thanks again for your awesome horizontal list view.

**Comment by valentasm1** [comment]
I solved this instead
observalbeCollection.Clear();
to
observalbeCollection = new ObservableCollection<DtoModel>();

**Comment by Mitke2011** [comment]
Hi guys,

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.SlowRecyclerView'.

error is more common then one can imagine and the stack trace does not offer any clue where to look for culprit (HUGE THANKS TO @valentasm1 ).  @roubachof, any chance you put this somewhere on your wiki or troubleshooting section?

As someone already said, thanks for the awesome horizontal list control! :)

**Comment by roubachof** [comment]
Create a new issue with the complete exception stack, and a repro sample.
I cannot help you with so little information
