### ISSUE TITLE
How to make horizontal list be cyclical ?

### ISSUE THREAD

**Issue by Kelve17** [roubachof/Sharpnado.Presentation.Forms#59]
Hi.
I know i should use` InifiniteListLoader` but i can't figure it out how to do it. The examples are not very clear for me and i could not understand. Do i need to create an `Paginator` instance on my view model ?

**Comment by roubachof** [comment]
Yes you need to use a paginator if you want to achieve infinite loading. You can learn more about it here: 

https://www.sharpnado.com/paginator-platform-independent/

**Comment by Kelve17** [comment]
Sry, i still can't understand. I feel like the examples u gave, are directly linked to your view models and can't seem to work outside of it...

**Comment by roubachof** [comment]
You can find an example here:

https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/Views/TabsLayout/ListView.xaml

https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/ViewModels/TabsLayout/ListPageViewModel.cs

**Comment by Kelve17** [comment]
Hi. I Dont understand at all xD. 

`        public Paginator<HomeMenuItem> Paginator { get => new Paginator<HomeMenuItem>(LoadAsync,pageSize:10,loadingThreshold:0.1f); }

        private async Task<PageResult<HomeMenuItem>> LoadAsync(int pageNumber, int pageSize, bool isRefresh)
        {
            PageResult<HomeMenuItem> resultPage = await _sillyDudeService.GetSillyPeoplePage(pageNumber, pageSize);
            var viewModels = resultPage.Items.Select(dude => new SillyDudeVmo(dude, GoToSillyDudeCommand)).ToList();

            SillyPeople.AddRange(viewModels);

            return resultPage;
        }`

What should i do on LoadAsync function ? Your code is too confuse for me. sorry

**Comment by roubachof** [comment]
Sorry mate, I think you hate to get some experience on mvvm async loading ;)
Also, even if you could successfully implement infinite loading, you can't achieve cyclical list view.
Cause infinite loading only works at the end of the list (not the begining)

**Comment by Kelve17** [comment]
Alright. thanks for the patience.

**Comment by Kelve17** [comment]
Also do u have any source on how to implement a new view? i would like to learn about this and i couldnt find any tutorial in the internet.
