### ISSUE TITLE
System.InvalidOperationException: The CollectionPadding, ItemSpacing and ItemWidth specified doesn't allow a single column to be displayed. MeasureHelper.ComputeSpan (System.Int32 availableWidth, Sharpnado.Presentation.Forms.RenderedViews.HorizontalListView element)

### ISSUE THREAD

**Issue by PaulsonMac** [roubachof/Sharpnado.Presentation.Forms#62]
Platform
 - OS: Android
 - Device: OPPO F7, A7 and other devices
 - Sdk vervion: Android 8.1.0
 - Xamarin.Forms: 3.4.0.1029999

Bug description 
App Crashes. 
System.InvalidOperationException: The CollectionPadding, ItemSpacing and ItemWidth specified doesn't allow a single column to be displayed

Steps To Reproduce
NA. I truly dont know how, I have never encountered it, these details are from my app's crash report.

Exceptions - Stack Trace
MeasureHelper.ComputeSpan (System.Int32 availableWidth, Sharpnado.Presentation.Forms.RenderedViews.HorizontalListView element)
ResponsiveGridLayoutManager.ComputeSpanCount (System.Int32 recyclerWidth)
ResponsiveGridLayoutManager.OnLayoutChildren (Android.Support.V7.Widget.RecyclerView+Recycler recycler, Android.Support.V7.Widget.RecyclerView+State state)
RecyclerView+LayoutManager.n_OnLayoutChildren_Landroid_support_v7_widget_RecyclerView_Recycler_Landroid_support_v7_widget_RecyclerView_State_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_recycler, System.IntPtr native_state)
(wrapper dynamic-method) System.Object.121(intptr,intptr,intptr,intptr).

**Comment by PaulsonMac** [comment]
Also occurs in Realme, vivo 1816, 1808. My .NET standard project has Xamarin Forms version 2.4.0.266-pre1 I dont want to update from this version for a specific reason.

**Comment by roubachof** [comment]
What is the nuget version?

**Comment by PaulsonMac** [comment]
Yes... It is 0.9.12. Thanks!

**Comment by roubachof** [comment]
I've changed the exception to an internal logging. But you may have an issue with your layout.
It seems in certain scenarios, while specifying ItemWidth +Padding + ItemSpacing, you the width of your parent layout is too small for displaying a single column.

**Comment by roubachof** [comment]
exception will not be raised in v1.2.0 
But you will maybe have some strange cases where the ui will be inconsistent (maybe maybe not :)

**Comment by PaulsonMac** [comment]
Thanks @roubachof , I'll review this and update you

**Comment by PaulsonMac** [comment]
> But you will maybe have some strange cases where the ui will be inconsistent (maybe maybe not :)

Yes, the UI is reflected in iOS, where the material frame border color is not working..!

```
<renderedViews:MaterialFrame BorderColor="#...." ......>
</enderedViews:MaterialFrame>
```
