### ISSUE TITLE
[Bug] Strange results when dealing with HeightRequest in a HorizontalListView Grid

### ISSUE THREAD

**Issue by NickeManarin** [roubachof/Sharpnado.Presentation.Forms#65]
**Platform (please complete the following information):**
 - OS: Android
 - Device Nokia 6.1 Plus/AndroidEmulator
 - Sdk vervion: Android SDK 28 (Pie)
 - Xamarin.Forms: 4.0.0.540366

**Describe the bug**
I'm trying to center vertically my ListView.
When setting the `HeightRequest` on a `HorizontalListView` in `Grid` mode, I'm getting strange results.

- If I set to `-1` it will adjust itself to fit one row of the grid, I would expect that it would try to fit all rows. The same happens if I don't set a `HeightRequest` but I put the `HorizontalListView` in a Grid and set the row to `Auto`.

- If set to the size of two rows (for example 350px), none of the rows will be rendered.

**To Reproduce**

```
    <Grid VerticalOptions="CenterAndExpand" HorizontalOptions="Center" WidthRequest="350">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        
        <Label Grid.Row="0" Text="Photos" Margin="0,10,0,5"/>
        <r:HorizontalListView Grid.Row="1" x:Name="MainListView" HorizontalOptions="FillAndExpand" VerticalOptions="Start" ColumnCount="3"
                              CollectionPadding="2" ItemSpacing="2" EnableDragAndDrop="True" ItemHeight="180" ItemsSource="{Binding Items, Mode=TwoWay}" ListLayout="Grid">
            <r:HorizontalListView.ItemTemplate>
                <DataTemplate>
                    <r:DraggableViewCell x:Name="DraggableViewCell">
                        <ContentView>
                            <Grid Margin="5">
                                <Label Text="{Binding Position, Mode=OneWay}" FontSize="20" Margin="8" VerticalOptions="Start" HorizontalOptions="Start"/>
                            </Grid>
                        </ContentView>
                    </r:DraggableViewCell>
                </DataTemplate>
            </r:HorizontalListView.ItemTemplate>
        </r:HorizontalListView>
    </Grid>
```

**Comment by roubachof** [comment]
I can have a look if you provide a sample

**Comment by roubachof** [comment]
closing after 24 days of inactivity

**Comment by NickeManarin** [comment]
Sorry, I ended up manually adjusting the height of the list by calculating the size of the elements.

This sample already has the working code: [Tap on Test, then Next]
https://github.com/NickeManarin/Xamarin.Demos2

If you put a `return;` in line 29 of PhotosView.xaml.cs, replace the alignments of the grid in line 11 of PhotosView.xaml with `VerticalOptions="Center" HorizontalOptions="Center"`, and set the HeighRequest of the list view to -1, you'll get the same result as mine, before the fix.
