### ISSUE TITLE
[HorizontalListView] ScrollEndedCommand doesn't fire

### ISSUE THREAD

**Issue by bnserig** [roubachof/Sharpnado.Presentation.Forms#67]
- OS: Android
- Device: Huawei P20 Lite
- Sdk vervion: Android SDK 27
- Xamarin.Forms: 3.6.0.344447

Sometimes ScrollEndedCommand doesn't fire. It appears when I scroll to the begin or the end of the HorizontalListView and the control doesn't have to re-center the ViewCell. Also CurrentIndex doesn't change.

French : Mon anglais étant plutôt limité, je vais essayer d'expliquer en français.
En fait j'arrive à reproduire ce cas quand j'essaye de scroller depuis le 2e élément vers le 1er (ou de l'avant dernier vers le dernier) en arrivant directement contre le bord, donc sans qu'il y ait l'animation de recentrage (j'utilise SnapStyle="Center"). J'arrive à le reproduire souvent quand je scrolle assez vite 2 fois d'affilée vers le bord.
J'espère m'être bien fait comprendre.

**Comment by roubachof** [comment]
compris :)

**Comment by roubachof** [comment]
Sorry can't reproduce :/
Maybe if you show me xaml

**Comment by bnserig** [comment]
I set a breakpoint in the ScrollEndedCommand. And sometimes it doesn't fire when i scroll quickly to to the first element.

XAML :
`<renderedViews:HorizontalListView
            x:Name="FruitList"
            Grid.Row="1"
            CollectionPadding="0"
            ColumnCount="1"
            HorizontalOptions="FillAndExpand"
            ItemSpacing="0"
            ListLayout="Linear"
            ScrollEndedCommand="{Binding ScrollEndedCommand}"
            ScrollSpeed="Normal"
            SnapStyle="Start"
            VerticalOptions="FillAndExpand">
            <renderedViews:HorizontalListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Label
                            Grid.Row="0"
                            BackgroundColor="LightGray"
                            HorizontalOptions="FillAndExpand"
                            HorizontalTextAlignment="Center"
                            Text="{Binding .}"
                            VerticalOptions="FillAndExpand"
                            VerticalTextAlignment="Center" />
                    </ViewCell>
                </DataTemplate>
            </renderedViews:HorizontalListView.ItemTemplate>
</renderedViews:HorizontalListView>`
