### ISSUE TITLE
Carousel effect with tab

### ISSUE THREAD

**Issue by MoeHamdan** [roubachof/Sharpnado.Presentation.Forms#68]
**Is your feature request related to a problem? Please describe.**
I want the  TabHostView  and ViewSwitcher to have the carousel effect? In other words make it work just like a tabstrip works on Android.[...]

Thank you very much for this amazing library.

**Comment by roubachof** [comment]
You can already :)
Use a TabHostView with the HorizontalList instead of the ViewSwitcher, and bind SelectedIndex to CurrentIndex.

**Comment by MoeHamdan** [comment]
Oh! You are awesome!!! That worked perfectly!

I have 1 more small question, how would I make the underlined part of the tab header to have the carousel effect? is that possible?

**Comment by roubachof** [comment]
unfortunately it would require a new implementation of the tabs for this...

**Comment by MoeHamdan** [comment]
I see thank you! I will try implementing the tab.

**Comment by roubachof** [comment]
You can create a feature request for this.
I will have time to improve tabs this summer :)

**Comment by MoeHamdan** [comment]
If I was successful I will pull request it. If not I will feature request it.

Again, Than you so much for this library!

**Comment by TienNK1987** [comment]
> You can already :)
> Use a TabHostView with the HorizontalList (with Carousel Layout) instead of the ViewSwitcher, and bind SelectedIndex to CurrentIndex.

Hi @roubachof, 
How to use HorizontalList (with Carousel Layout) instead of ViewSwitcher with different content in each tab? As I know, HorizontalListView has only one DataTemplate to declare its content.

Thank you for your amazing lib.

**Comment by roubachof** [comment]
With a DataTemplateSelector :)

**Comment by TienNK1987** [comment]
> With a DataTemplateSelector :)
Could you please give me a sample?
Thank you @roubachof,

**Comment by roubachof** [comment]
https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector

**Comment by TienNK1987** [comment]
> https://docs.microsoft.com/en/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector

Thank you for the quick response.

Sorry for my stupid question. How can I do this with different DataType and DataSource in each tab? For example: In tab 1, I have a list of Student, In tab 2 I have a list of Teacher, In tab 3 I have a list of Class. How can I do that with TabHostView and HorizontalListView and DataTemplateSelector?

Thank you very much.

**Comment by TienNK1987** [comment]
Hi @roubachof,

Could you please help me, I still cannot swipe between tabs.
Currently, I'm using TabHostView and ViewSwitcher.  Please show me how to change to use HorizontalList (with Carousel Layout) instead of ViewSwitcher as you said.
I have 3 tabs with 3 different types of DataType and DataSource. 
In tab1 is a list of Student, tab2 is a list of Teacher, tab3 is a list of Class.

Waiting for your response, thank you very much.

**Comment by TienNK1987** [comment]
I still cannot swipe to change tabs using TabHostView and ViewSwitcher.
Anyone can help? Thanks.
