### ISSUE TITLE
System.NullReferenceException being thrown when I try to set frame's content to a HorizontalListView

### ISSUE THREAD

**Issue by gogolon** [roubachof/Sharpnado.Presentation.Forms#76]
**Platform (please complete the following information):**
 - OS: Android (I haven't checked on iOS
 - Device: Xiaomi Redmi 4x
 - Sdk vervion: Android SDK 21
 - Xamarin.Forms: 4.1.0.618606

**Describe the bug**
I'm unable to use the HorizontalListView due to an exception (NullReferenceException) being thrown when I try to set it as a content of a layout or frame. The layout / frame is not null.

**To Reproduce**
1.  Initialize a frame:
```
            myFrame = new Frame()
            {
                      .....
            };
```
2. Set frame's content to a HorizontalListView
`myFrame.Content = new HorizontalListView();
`
**Exceptions (if applicable)**
System.NullReferenceException is being thrown in an external code, hence there's no stack trace available.

**Comment by roubachof** [comment]
can I have the full Exception stack please?

**Comment by gogolon** [comment]
I'm not sure what you want me to do. The VS just shows that the exception is being thrown in an external code. These are the last 3 lines of output.
```
08-01 19:51:12.897 D/Mono    ( 9268): Assembly Ref addref Sharpnado.Presentation.Forms.Droid[0x7f6ed44800] -> Sharpnado.Infrastructure[0x7f6ed44400]: 2
Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by roubachof** [comment]
Well I can do nothing with that for sure :)

Have you added the nuget package on all the platforms ?
Have you initialized the library in the Activity / AppDelegate ?

**Comment by gogolon** [comment]
It turned out that I forgot to initialize the plugin. I'm really sorry for wasting your time.

**Comment by gogolon** [comment]
Yes, the nuget is added on all platforms and the plugin is initialized. For some reason VS showed me the exception details once. It is being thrown in my page's OnSizeAllocated event.

```
protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height); // line of exception
            this.width = width;
            this.height = height;
        }
```

**Comment by roubachof** [comment]
if you create a repo I can have a look at your sample.

**Comment by gogolon** [comment]
After adding a proper ItemTemplate (I kept forgetting to wrap my control in a ViewCell) the exception stopped being thrown. I'm sorry for wasting your time.

**Comment by roubachof** [comment]
No worries man, I'm happy my component is useful to you.
