### ISSUE TITLE
How to prevent a ListView from scrolling to the beginning at the ItemsSource update?

### ISSUE THREAD

**Issue by gogolon** [roubachof/Sharpnado.Presentation.Forms#77]
Hello,
My ItemsSource is a list containing always the same objects, but I sometimes change their order and set the ItemSource again (to refresh the listview). After doing so, the listview scrolls to the first item. I tried setting the CurrentIndex property to the index before update, but it doesn't work. How to keep the same CurrentIndex regardless of refreshments?
[EDIT]: This only happens on Android, so I think this might be a bug.

**Comment by roubachof** [comment]
This is how the RecyclerView works on android, I don't think I can do anything agains that.
