### ISSUE TITLE
List goes blank after reset event

### ISSUE THREAD

**Issue by nielsenko** [roubachof/Sharpnado.Presentation.Forms#81]
When an item source raises a `CollectionChanged` event with action `NotifyCollectionChangedAction.Reset`, then `_dataSource` is simply cleared.

```
case NotifyCollectionChangedAction.Reset:
  _dataSource.Clear();
  parentView.GetRecycledViewPool().Clear();
  NotifyDataSetChanged();
  break;
```

Hence the list view goes blank, instead of actually re-evaluating the `ItemsSource`, at least for me.

Platform used during testing
 - OS: Android
 - Device: Nexus 5x, Honeywell EDA51
 - Sdk version: Android SDK 21+
 - Xamarin.Forms: 4.1.0-sr3

**Comment by roubachof** [comment]
I don't think I will support the semantic you gave about the ```Reset``` action (re-evaluating vs clearing), because: 

1. ObservableCollection only sends Reset action when collection has been cleared.

```csharp
protected override void ClearItems()
    {
      this.CheckReentrancy();
      base.ClearItems();
      this.OnCountPropertyChanged();
      this.OnIndexerPropertyChanged();
      this.OnCollectionReset();
    }
```

2. [Offical doc](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedaction?view=netstandard-2.0)


Reset | 4 | The content of the collection was cleared.
-- | -- | --


If your ```ItemsSource``` changed a lot, just raise the property changed from your view model, and the view source / recycler adapter will be refreshed.

**Comment by nielsenko** [comment]
I think this actually changed with .NET 4.5. I'm old enough to remember different semantics for `Reset`, aka _lots has happened, please re-evaluate your binding_ :-) 

Anyway, fx `DynamicData.Binding.ObservableCollectionExtended` will simply raise a `Reset` after notification has been suspended. Similar using `DynamicData.IObservable<IChangeSet<T>>.Bind` has a `resetThreshold` argument (that defaults to 25) for how many changes to track before simply raising a reset event, instead of creating an storm of `Add`s, `Remove`s etc. So to play nice with _DynamicData_ you might consider to reconsider? I would love to be able to use it together with _Sharpnado_.

**Comment by nielsenko** [comment]
I tried using your suggested workaround, ie. raising a `PropertyChanged` event on the property that `ItemsSource` is bound to, just after the `CollectionChanged` `Reset` event, but the control stays blank :-/

**Comment by roubachof** [comment]
Ok you won :)
Since the old semantic is backward compatible with the new one.

**Comment by nielsenko** [comment]
:pray: Thank you. Do you have a target date for your next release? No promises, just a vague idea?

**Comment by roubachof** [comment]
It will be published in September.
