### ISSUE TITLE
UWP?

### ISSUE THREAD

**Issue by papiermache** [roubachof/Sharpnado.Presentation.Forms#84]
is supported?

**Comment by InquisitorJax** [comment]
@papiermache I believe there was already an issue for this https://github.com/roubachof/Sharpnado.Presentation.Forms/issues/60

... would be great if it was on the roadmap though - I would love the tabs control for UWP! :)

**Comment by roubachof** [comment]
though I didn't really test it, the tabs should work in UWP :)

**Comment by InquisitorJax** [comment]
I did a quick test for UWP, and it looks to be working! :) 
![image](https://user-images.githubusercontent.com/1822976/75821328-b7555a80-5da6-11ea-96c3-68b08730f1d9.png)
