### ISSUE TITLE
Footer or prevent drag

### ISSUE THREAD

**Issue by GW-FUB** [roubachof/Sharpnado.Presentation.Forms#85]
**Is your feature request related to a problem? Please describe.**
I got a list of items in my HorizontalListView (just 1 column) with an add button at the end. I would like to drag the items, but not the add button. The button should scroll with the others though, like a footer in the usual listview.

**Describe the solution you'd like**
I would like to have an option like a footer or a "disable drag" option for the items.

**Describe alternatives you've considered**
At the moment I will just let the button draggable and if the user clicks it the item will be added at its current position.

**Additional context**
Picture of the app:
![grafik](https://user-images.githubusercontent.com/23636756/65663186-60e53280-e036-11e9-91ba-4463c15e7732.png)

**Comment by danilkurkin1** [comment]
@GW-FUB  Dont think you need any code change from sharpnado. Simply use XF Absolute, relative or Grid layout to position the button on the top of your listview.

**Comment by GW-FUB** [comment]
@danilkurkin1 But then it's not scrollable, right? There is no possibility to put it into the list?

**Comment by roubachof** [comment]
mmmh. Maybe I can implement this with the DraggableCell...

**Comment by roubachof** [comment]
It will be implemented with the bindable property `DraggableViewCell.IsDraggable` in the version 1.4.
