### ISSUE TITLE
[TypeLoadException] AndroidHorizontalListViewRenderer.UpdateItemsSource()

### ISSUE THREAD

**Issue by alexmanie** [roubachof/Sharpnado.Presentation.Forms#87]
**Platform (please complete the following information):**
 - OS: Android
 - Device: Redmi Note 4
 - Sdk vervion: Android 7.0
 - Xamarin.Forms: 4.0.0.618610

**Describe the bug**
Error while executing the application in Release mode.
While we test the app in Debug, no error is thrown.

**Exception**
```
System.TypeLoadException: Could not load type of field 'Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.ViewHolderQueue:_views' (1) due to: Could not resolve type with token 0100004e from typeref (expected class 'System.Collections.Generic.Queue`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Collections.Generic.Queue`1 member:(null)
```

**Comment by gogolon** [comment]
I have a very similar issue. Downgrading works, but I would like to use the newest version of the package:

> Unhandled Exception:
> 
> System.TypeLoadException: Could not load type of field 'Sharpnado.Presentation.Forms.Droid.Renderers.HorizontalList.ViewHolderQueue:_views' (1) due to: Could not resolve type with token 0100004e from typeref (expected class 'System.Collections.Generic.Queue`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Collections.Generic.Queue`1 member:(null) occurred

**Comment by roubachof** [comment]
can't reproduce... 
Will need a sample to investigate

**Comment by roubachof** [comment]
closing this due to lack of sample
