### ISSUE TITLE
Customisation of transition speed between views for HorizontalListView 

### ISSUE THREAD

**Issue by ssmsexe** [roubachof/Sharpnado.Presentation.Forms#9]
**Is your feature request related to a problem? Please describe.**
Transition speed between the views for HorizontalListView is not customizable.

**Describe the solution you'd like**
It would be useful to have transition speed as a bindable property in the shared project or make the platform specific implementation extendible to be able to extend the "StartSnapHelper" and "SnappingCollectionViewLayout" in platform specific.

**Comment by roubachof** [comment]
I would prioritize this less than the auto size of the ItemHeight, but I can see the point :)

**Comment by roubachof** [comment]
won't happen.
