### ISSUE TITLE
Navigation don't work after reopen my app from background!

### ISSUE THREAD

**Issue by mosi1380** [roubachof/Sharpnado.Presentation.Forms#93]
Hi, When i press back button on android to get out the app, and then open it again, navigation don't work.
My View Models inherit from ANavigationService class like you.
Please help us. thanks.

**Comment by roubachof** [comment]
Well it has nothing to do with the components from this package I'm afraid. ANavigationService is a service I created for the silly app, I offer no support on it.

**Comment by mosi1380** [comment]
Ok, thanks. well done.
