### ISSUE TITLE
Crash when HorizontalListView Initialize

### ISSUE THREAD

**Issue by amer2737** [roubachof/Sharpnado.Presentation.Forms#96]
**Platform (please complete the following information):**
 - OS: [iOS/Android/Both]
 - Device: [iPhone6/iPhoneSimulator/Pixel/AndroidEmulator/...]
 - Sdk vervion: [iOS 11/Android SDK 28]
 - Xamarin.Forms: [4.4.0.991265]

**Describe the bug**
When add HorizontalListView the App is crash 
in same code and same MVVM when add normal ListView it is work
these is my XAML 

             <renderedViews:HorizontalListView
                Margin="-16,8"
                CollectionPadding="40,10"
                ColumnCount="1"
                ItemHeight="144"
                ItemSpacing="20"
                ItemWidth="144"
                ItemsSource="{Binding ProductsHomesList}"
                ListLayout="Linear"
                SnapStyle="Center">
                <renderedViews:HorizontalListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <StackLayout>
                                <Label
                                    FontSize="Body"
                                    Text="{Binding title}"
                                    TextColor="White" />
                            </StackLayout>
                        </ViewCell>
                    </DataTemplate>
                </renderedViews:HorizontalListView.ItemTemplate>
            </renderedViews:HorizontalListView>

is it need any Initialize on Andriod or IOS ??
 
**Exceptions (if applicable)**
Copy paste the exception and the stack trace
```
Exception:
Object reference not set to an instance of an object
```

**Screenshots (if applicable)**

**Comment by roubachof** [comment]
IMPORTANT: On platform projects, call SharpnadoInitializer.Initialize() after Xamarin.Forms.Forms.Init() and before LoadApplication(new App()).

Those components are used and tested in the Silly! app: https://github.com/roubachof/Xamarin-Forms-Practices.

**Comment by roubachof** [comment]
Also if you set the ColumnCount, you cannot set the ItemWidth at the same time cause it will be auto computed
