### ISSUE TITLE
BottomTabItem of TabHostView Can use Icon Font

### ISSUE THREAD

**Issue by carl-neng** [roubachof/Sharpnado.Presentation.Forms#97]
**Use Icon font**
For Bottom tab item I need to include multiple asset resources to each project and any type of device sometime confused or forget include it. So I want to request this feature for use assets for tab icon.

**My idea**
I want to use icon font:
1. Easy to manage asset resources in one file.
2. Create small binary (.ipa, apk or aab) size when we published to market.

**Comment by TheBaileyBrew** [comment]
Using FontImageSource as a valid IconImageSource would be great!

**Comment by roubachof** [comment]
will be available in v1.4

**Comment by carl-neng** [comment]
Hi @roubachof I see your version v1.4 available on nuget but I didn't know you have include tab icon use font icon or not?

**Comment by roubachof** [comment]
Use a FontImageSource for the IconImageSource and it will work just fine.
https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/text/fonts#display-font-icons

**Comment by carl-neng** [comment]
Hi @roubachof Yes, thank you so much it worked as well.
