### ISSUE TITLE
System.TypeLoadException has been thrown with ViewModelLoader

### ISSUE THREAD

**Issue by TBertuzzi** [roubachof/Sharpnado.Presentation.Forms#98]
- Xamarin.Forms: [4.4.*.*]

Every time I try to use ViewModelLoader I get the error . Could not resolve type with token 0100004a from typeref (expected class 'Sharpnado.Presentation.Forms.ViewModels.ViewModelLoader`1' in assembly 'Sharpnado.Presentation.Forms, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null')

I am using both referenced packages. They are referenced in the iOS project and the shared project. This error occurs when debugging iOS project

**Comment by TBertuzzi** [comment]
Same error using TabHost.

**Comment by TheBaileyBrew** [comment]
If I leave the ViewSwitcher empty with no views to load then my app runs without a hitch. But once I add views, my app crashes at Initial load:

System.TypeLoadException has been thrown
Invalid generic instantiation

**Comment by roubachof** [comment]
I would need more info. Can't do anything with such little information, sorry.

**Comment by TheBaileyBrew** [comment]
This repo is a dummy app created with all the default pages in XF on Mac. I can get the tabs and button to show, but none of the views can be added to the ViewSwitcher, and I'm not sure what's being done wrong on my end or I'm just missing something.

https://github.com/TheBaileyBrew/Testing_Tabs

**Comment by roubachof** [comment]
Well it's pretty simple:

The binding context of this:
```
<customViews:LazyView x:TypeArguments="views:ItemsPage"
                                      BindingContext="{Binding ItemsViewModel}"
                                      AccentColor="Aqua"/>
                <customViews:LazyView x:TypeArguments="views:AboutPage"
                                      BindingContext="{Binding AboutViewModel}"
                                      AccentColor="Blue"/>
```
is this:

```
namespace Testing_Tabs.ViewModels
{

    [AddINotifyPropertyChangedInterface]
    public class AppTabsViewModel : Sharpnado.Presentation.Forms.ViewModels.Bindable
    {
        public int SelectedViewModelIndex { get; set; }

        public AppTabsViewModel()
        {
        }
    }
}
````

And as you can see there is no `ItemsViewModel` or `AboutViewModel` in it...

**Comment by TheBaileyBrew** [comment]
Removing the BindingContexts from MainPage and leaving it as this:

`
<customViews:LazyView x:TypeArguments="views:ItemsPage"
                                      AccentColor="Aqua"/>
                <customViews:LazyView x:TypeArguments="views:AboutPage"
                                      AccentColor="Blue"/>
`

**Comment by roubachof** [comment]
Oh yes, the `ViewSwitcher` deals with `View` not `ContentPage`

**Comment by TheBaileyBrew** [comment]
So, then how do I define the binding context so it doesn't crash at InitializeComponent() on MainPage?

The only way I don't get a crash is when I remove the LazyViews completely. Maybe I just don't understand how the process works, and I need to look at your implementation guide again.

**Comment by TheBaileyBrew** [comment]
![image](https://user-images.githubusercontent.com/35344621/72271759-78e8be00-35f5-11ea-90e2-080d7db5bdc5.png)


`  at Testing_Tabs.Views.MainPage..ctor () [0x0001d] in /Users/matthew.bailey/Projects/Testing_Tabs/Testing_Tabs/Views/MainPage.xaml.cs:19 
  at Testing_Tabs.App..ctor () [0x0000f] in /Users/matthew.bailey/Projects/Testing_Tabs/Testing_Tabs/App.xaml.cs:17 
  at Testing_Tabs.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x0000e] in /Users/matthew.bailey/Projects/Testing_Tabs/Testing_Tabs.iOS/AppDelegate.cs:30 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.8.3.0/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.8.3.0/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Testing_Tabs.iOS.Application.Main (System.String[] args) [0x00001] in /Users/matthew.bailey/Projects/Testing_Tabs/Testing_Tabs.iOS/Main.cs:17 `

**Comment by roubachof** [comment]
The object you put in your view switcher must inherit from `View` not from `ContentPage`.
So your `ItemsPage` should be a `ItemsView : ContentView`.

see here: https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/Views/TabsLayout/HomeView.xaml

**Comment by TheBaileyBrew** [comment]
Ah! Gotcha, so any OnAppearing() - OnDissappearing() content will have to be handled manually. I think I can manage that.

**Comment by TBertuzzi** [comment]
My error In TaskView : 

Could not load type of field 'SharpnadoExemplo.ViewModels.MainViewModel:<Pokemons>k__BackingField' (0) due to: Could not resolve type with token 0100006a from typeref (expected class 'Sharpnado.Presentation.Forms.ViewModels.ViewModelLoader`1' in assembly 'Sharpnado.Presentation.Forms, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null') assembly:Sharpnado.Presentation.Forms, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null type:Sharpnado.Presentation.Forms.ViewModels.ViewModelLoader`1 member:(null)

<img width="1259" alt="Captura de Tela 2020-01-14 às 10 05 00" src="https://user-images.githubusercontent.com/22523732/72346823-7352ad00-36b5-11ea-9047-1c6401123829.png">

Sample : https://github.com/TBertuzzi/SharpnadoExemplo/tree/feature/TaskView

**Comment by roubachof** [comment]
I will get back to you shortly. Unfortunately your issue has been hijacked x)

**Comment by roubachof** [comment]
So first ty for the repo sample, it has been really easy to find your issue :)

1. You are referencing BOTH `Presentation.Forms` and `HorizontalListView` nuget packages. But the `HorizontalListView` is included in the `Presentation.Forms` package
2.  The XF and Essentials version is not the same in your `Core` project and `Android` project creating those typeref issues. Just update your android csproj to the same version everywhere else and it will be fine

SharpnadoExemplo.Android.csproj:

```xml
<ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.4.0.991537" />
    <PackageReference Include="Xamarin.Essentials" Version="1.3.1" />
    <PackageReference Include="Sharpnado.Presentation.Forms">
      <Version>1.3.0</Version>
    </PackageReference>
  </ItemGroup>
```

And also: nice blog post :)
